### ISSUE TITLE
[Storage] V4 Signature Support for virtual hosted-style signed 

### ISSUE THREAD

**Issue by frankyn** [googleapis/python-storage#10]
Tracking issue for work defined in companion document.

[New Client Request - Support for virtual hosted-style signed URLs](https://docs.google.com/document/d/1TkoDiZjz6nINNVQrYbrfaODhmcMTR-crb94aR1cXZVA/edit#)

**Comment by tseaver** [comment]
Analysis:

- `_signing.generate_signed_url_v4` already supports this feature via its `api_access_endpoint` argument.
- We could add a `virtual_host` flag to `Blob.generate_signed_url` and `Bucket.generate_signed_url` which defaults `False` for now (following Option 2 in the spec).  If set to `True`, then the blob/bucket would pass in the appropriate `api_access_endpoint`, along with the shorter `resource`.

**Comment by HemangChothani** [comment]
@tres Thanks for the analysis, the same is implemented and it's under the
internal review process.

**Comment by frankyn** [comment]
Missing conformance tests
