### ISSUE TITLE
Uploading blobs to Cloud Storage with `upload_from_string` sometimes results in a strange SSLError

### ISSUE THREAD

**Issue by Cupcee** [googleapis/python-storage#1037]
Our Cloud Run service serves around 200-300 requests a day and as a part of the request is 2-3 calls to the cloud storage API. During the past 2 days we've gotten 3 strange errors that complain about a closed socket (error in _ssl.c line 2393 results from closed socket connection). This issue has been raised [before](https://github.com/googleapis/python-storage/issues/984) too, but was closed.

This error occurs quite rarely, but enough to be bothersome as it means 1-2 requests during the past few days have failed.

#### Environment details

  - OS type and version: Linux (Debian) Docker image running on Cloud Run
  - Python version: Python 3.11.2
  - pip version: `pip --version`
  - `google-cloud-storage` version: `2.7.0`

#### Steps to reproduce

  1. Try to upload a `BytesIO` image file to Google Cloud Storage with `upload_from_string` function
  2. (Rarely) upload throws the SSLError: `requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/coiniverse-bucket/o?uploadType=multipart (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2393)')))`

#### Code example

```python
def save_bytesio_to_bucket(
    bucket: storage.Bucket, image_dir: str, filename: str, file: BytesIO
) -> str:
    day = date.today().strftime("%Y_%m_%d")
    blob_path = f"{image_dir}/{day}/{filename}.jpg"
    bucket.blob(blob_path).upload_from_string(
        file.getvalue(), content_type="image/jpeg"
    )
    return blob_path
```

#### Stack trace
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/coiniverse-bucket/o?uploadType=multipart (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2393)')))",2023-05-06T09:01:50.110687Z,,
    raise SSLError(e, request=request)",2023-05-06T09:01:49.015645Z,,
  File ""/usr/local/lib/python3.11/site-packages/requests/adapters.py"", line 563, in send",2023-05-06T09:01:49.015640Z,,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",2023-05-06T09:01:49.015635Z,,
    r = adapter.send(request, **kwargs)",2023-05-06T09:01:49.015631Z,,
  File ""/usr/local/lib/python3.11/site-packages/requests/sessions.py"", line 701, in send",2023-05-06T09:01:49.015625Z,,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",2023-05-06T09:01:49.015620Z,,
    resp = self.send(prep, **send_kwargs)",2023-05-06T09:01:49.015615Z,,
  File ""/usr/local/lib/python3.11/site-packages/requests/sessions.py"", line 587, in request",2023-05-06T09:01:49.015611Z,,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",2023-05-06T09:01:49.015607Z,,
    response = super(AuthorizedSession, self).request(",2023-05-06T09:01:49.015602Z,,
  File ""/usr/local/lib/python3.11/site-packages/google/auth/transport/requests.py"", line 549, in request",2023-05-06T09:01:49.015598Z,,
             ^^^^^^^^^^^^^^^^^^",2023-05-06T09:01:49.015593Z,,
    result = transport.request(",2023-05-06T09:01:49.015588Z,,
  File ""/usr/local/lib/python3.11/site-packages/google/resumable_media/requests/upload.py"", line 145, in retriable_request",2023-05-06T09:01:49.015583Z,,
               ^^^^^^",2023-05-06T09:01:49.015575Z,,
    response = func()",2023-05-06T09:01:49.015569Z,,
  File ""/usr/local/lib/python3.11/site-packages/google/resumable_media/requests/_request_helpers.py"", line 148, in wait_and_retry",2023-05-06T09:01:49.015564Z,,
    raise error",2023-05-06T09:01:49.015557Z,,
  File ""/usr/local/lib/python3.11/site-packages/google/resumable_media/requests/_request_helpers.py"", line 171, in wait_and_retry",2023-05-06T09:01:49.015550Z,,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",2023-05-06T09:01:49.015544Z,,
    return _request_helpers.wait_and_retry(",2023-05-06T09:01:49.015540Z,,
  File ""/usr/local/lib/python3.11/site-packages/google/resumable_media/requests/upload.py"", line 153, in transmit",2023-05-06T09:01:49.015535Z,,
               ^^^^^^^^^^^^^^^^",2023-05-06T09:01:49.015530Z,,
    response = upload.transmit(",2023-05-06T09:01:49.015526Z,,
  File ""/usr/local/lib/python3.11/site-packages/google/cloud/storage/blob.py"", line 1889, in _do_multipart_upload",2023-05-06T09:01:49.015522Z,,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^",2023-05-06T09:01:49.015516Z,,
    response = self._do_multipart_upload(",2023-05-06T09:01:49.015511Z,,
  File ""/usr/local/lib/python3.11/site-packages/google/cloud/storage/blob.py"", line 2354, in _do_upload",2023-05-06T09:01:49.015508Z,,
                   ^^^^^^^^^^^^^^^^",2023-05-06T09:01:49.015503Z,,
    created_json = self._do_upload(",2023-05-06T09:01:49.015499Z,,
  File ""/usr/local/lib/python3.11/site-packages/google/cloud/storage/blob.py"", line 2539, in upload_from_file",2023-05-06T09:01:49.015494Z,,
    self.upload_from_file(",2023-05-06T09:01:49.015489Z,,
  File ""/usr/local/lib/python3.11/site-packages/google/cloud/storage/blob.py"", line 2814, in upload_from_string",2023-05-06T09:01:49.015485Z,,
    bucket.blob(blob_path).upload_from_string(",2023-05-06T09:01:49.015480Z,,
  File ""/app/src/cloud_storage.py"", line 26, in save_bytesio_to_bucket",2023-05-06T09:01:49.015475Z,,
                ^^^^^^^^^^^^^^^^^^^^^^^",2023-05-06T09:01:49.015470Z
```

**Comment by cojenco** [comment]
Hi @Cupcee thanks for the detailed report. Could you also share your pip freeze? It'd be useful for us to know what versions of google-resumable-media and requests are being used.


I suspect that the transient SSL errors may be caused by connection issues. The `requests.exceptions.SSLError` is a subclass of `requests.exceptions.ConnectionError` and is tracked as a [retryable error](https://github.com/googleapis/google-resumable-media-python/blob/f25e6df2df0a0bf98dd2b08c096aa4b7cc27fe4a/google/resumable_media/requests/_request_helpers.py#L42) in the `google-resumable-media` in version 2.1.0+

However, note that uploads are not idempotent in the GCS API. Therefore, the client will not retry failures by default unless the user has set an if_generation_match precondition. 

I'd suggest to use an `if_generation_match` precondition and retry the upload in this case. See guidance on [retry strategy](https://cloud.google.com/storage/docs/retry-strategy#client-libraries) and [request preconditions](https://cloud.google.com/storage/docs/request-preconditions). See sample codes [here](https://cloud.google.com/storage/docs/retry-strategy#tools) and [here](https://cloud.google.com/storage/docs/samples/storage-upload-file#storage_upload_file-python). Assuming the upload is for a new file, set `if_generation_match=0`, similar to something as below

```
def save_bytesio_to_bucket(
    bucket: storage.Bucket, image_dir: str, filename: str, file: BytesIO
) -> str:
    day = date.today().strftime("%Y_%m_%d")
    blob_path = f"{image_dir}/{day}/{filename}.jpg"
    bucket.blob(blob_path).upload_from_string(
        file.getvalue(), content_type="image/jpeg", if_generation_match=0
    )
    return blob_path
```

**Comment by cojenco** [comment]
Hope this helps and thank for sharing!

I'd also recommend updating the libraries to the latest versions
[google-resumable-media==2.5.0](https://github.com/googleapis/google-resumable-media-python/releases/tag/v2.5.0) where we've added other know connection errors as retryable errors;
[google-cloud-storage==2.9.0](https://github.com/googleapis/python-storage/releases) where "transfer_manager" module for concurrent uploads and downloads is introduced as a preview feature

Feel free to reopen this issue if you have further questions.
