### ISSUE TITLE
Missing Transfer Manager documentation in cloud docs

### ISSUE THREAD

**Issue by frankyn** [googleapis/python-storage#1083]
Hi team,

I wanted to share docs to Python Transfer Manager but they're not visible in our public docs: https://screenshot.googleplex.com/BGJZ6wH4hgHvrEi

**Comment by cojenco** [comment]
AFAIK there is work planned for Transfer Manager documentation with the tech writing team. @andrewsg if we want to generate/publish the python cloud docs first, we can update https://github.com/googleapis/python-storage/blob/main/docs/index.rst and the docs/ directory.

**Comment by cojenco** [comment]
Update - Public documentation on c.g.c will be generated upon library release (v2.10.1)
