### ISSUE TITLE
[Storage] V4 Signature Signed URLs With Bucket-Bound Hostnames

### ISSUE THREAD

**Issue by frankyn** [googleapis/python-storage#11]
Tracking issue for work defined in companion document.

[New Client Request - Support for Bucket-Bound Hostnames With GCS Signed URLs](https://docs.google.com/document/d/1Da8LQEmc1OKRECxXqdivQa4tcTEImlti_fVYzoh4reI)

**Comment by tseaver** [comment]
Analysis:

- `_signing.generate_signed_url_v4` already supports this feature via its `api_access_endpoint` argument.
- We could add a `use_cname` flag to `Blob.generate_signed_url` and `Bucket.generate_signed_url` which defaults `None`.  If set, then the blob/bucket would pass in the value or the argument as  `api_access_endpoint`, along with the shorter `resource`.
- If `use_cname` is passed as a bare hostname, we also need to provide a way for the user to signal that they want an HTTPS URL.

**Comment by HemangChothani** [comment]
@tseaver have you started working on this?if not then may i work on this issue?

**Comment by tseaver** [comment]
On 2/26/20 12:22 AM, HemangChothani wrote:
> @tseaver <https://github.com/tseaver> have you started working on this?if not 
> then may i work on this issue?

I do have a PR in progress -- thanks for checking!


Tres.
-- 
==================================================
Tres Seaver  540-429-0999    tseaver@palladion.com
Palladion Software            http://palladion.com
