### ISSUE TITLE
Blob.from_string() should be able to parse all valid gcs uri

### ISSUE THREAD

**Issue by pPanda-beta** [googleapis/python-storage#1107]
`Blob.from_string` is terminating parsing of object names at hash(`#`) character. 

## Test Code (minimalistic)
```python3
from google.cloud import storage
blob = storage.Blob.from_string('gs://my-bucket/my/problamatic/object#name')
print(blob.name)
# my/problamatic/object
```
## Expected
Object name should be `my/problamatic/object#name`
## Actual
Object name found is `my/problamatic/object`

## Temporary Workaround
```python3
import re
from google.cloud import storage
GS_PATTERN = re.compile(r"gs://(?P<bucket_name>[^/]+)/(?P<object_name>.+)")

m = GS_PATTERN.match('gs://my-bucket/my/problamatic/object#name')
blob = storage.Bucket(name=m.group('bucket_name'), client=None).blob(m.group('object_name'))
print(blob.name)
# my/problamatic/object#name
```

## Version
`google_cloud_storage-2.10.0-py2.py3-none-any.whl`

## Suggestion
`urlsplit` is not a good utility for parsing gcs uris. I have seen problems with `%` char, trailing `?`, ... etc with `urlsplit`. Most of those characters are valid in context of gcs object names.

https://github.com/googleapis/python-storage/blob/663edc5e803f327f9c4eba86a75206d2e46c8536/google/cloud/storage/blob.py#L406

**Comment by cojenco** [comment]
Thanks for filing. I understand how this could cause a parsing issue. I will work with the team to address next steps.
 
Please note that we strongly recommended users to avoid `#` and control characters in object names, see more details in the [official documentation](https://cloud.google.com/storage/docs/objects#naming).

**Comment by frankyn** [comment]
Adding findings from Node.js storage after our conversation @cojenco.

Node.js does not yet support a similar method to this but has a [FR](https://github.com/googleapis/nodejs-storage/issues/1898) for it: 

However, the client does support gcs URI's in [File#copy()](https://googleapis.dev/nodejs/storage/latest/File.html#copy) and move(). It does support `#` as part of the object name. Here's an example:

```javascript
(async () => {
  const {Storage} = require('@google-cloud/storage');

  const bucketName = "bucket-name";

  const storage = new Storage();

  const file = storage.bucket(bucketName).file('object-name');
  const [newFile] = await file.copy("gs://bucket-name/new-year-new-me#random");
  const [metadata] = await newFile.getMetadata();
  console.log(metadata); // Logs metadata and contains object name with `#`
})();
```
