### ISSUE TITLE
Blob client 'from_string' method regex does not allow bucket root

### ISSUE THREAD

**Issue by mcompen** [googleapis/python-storage#1183]
#### Environment details

  - All OS types and Python versions

#### Steps to reproduce

Create a Blob client with the `from_string` method at bucket root.

#### Code example

```python
from google.cloud import storage

project = "project"
credentials = "credentials"
storage_client = storage.Client(project=project, credentials=credentials)
storage.Blob.from_string(
        uri="gs://bucket_name",
        client=storage_client,
    )
```

#### Stack trace
```
"/Users/manu.compen/Library/Caches/pypoetry/virtualenvs/bla-py3.9/lib/python3.9/site-packages/google/cloud/aiplatform/pipeline_jobs.py", line 404, in submit
    gcs_utils.create_gcs_bucket_for_pipeline_artifacts_if_it_does_not_exist(
  File "/Users/manu.compen/Library/Caches/pypoetry/virtualenvs/bla-py3.9/lib/python3.9/site-packages/google/cloud/aiplatform/utils/gcs_utils.py", line 237, in create_gcs_bucket_for_pipeline_artifacts_if_it_does_not_exist
    pipelines_bucket = storage.Blob.from_string(
  File "/Users/manu.compen/Library/Caches/pypoetry/virtualenvs/bla-py3.9/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 410, in from_string
    raise ValueError("URI scheme must be gs")
ValueError: URI scheme must be gs
```
I came across this (as you can see in the stacktrace) using the `aiplatform` package to submit a Vertex Pipeline job where you have to specify a bucket root, but I think the bug is on this side of the fence.

**Comment by m-rath** [comment]
Same problem here. Using `aiplatform.init(staging_bucket="gs://my_staging_bucket")`. 
Or just `storage.Blob.from_string("gs://my_staging_bucket")`. Same Value error. Not sure how to circumvent. Thanks

**Comment by cojenco** [comment]
Thanks for filing. `Blob.from_string` is intened to get a constructor for blob object with a blob URI. The blob URI should include a object name such as `gs://bucket_name/object_name`

For a bucket root, it'd make more sense to use the Bucket class method `Bucket.from_string`. I believe this is a bug in the aiplatform where there is a misusage of `Blob.from_string` [here](https://github.com/googleapis/python-aiplatform/blob/45d599b7c7ca1652c0559f872cf30e5afc1b0e33/google/cloud/aiplatform/utils/gcs_utils.py#L237-L240). Changing to use `Bucket.from_string` should fix the issue. I'll go ahead and file an issue in the aiplatform repository.

**Comment by cojenco** [comment]
I see that https://github.com/googleapis/python-aiplatform/issues/2936 is already filed along with a fix https://github.com/googleapis/python-aiplatform/pull/2948 
Thank you @mcompen

**Comment by mcompen** [comment]
Closing this as the issue is with the aiplatform package and I opened an issue there.

**Comment by Ark-kun** [comment]
> Blob.from_string is intened to get a constructor for blob object with a blob URI. The blob URI should include an object name such as gs://bucket_name/object_name

What is the prescribed way to get a `Bucket` object for a given `gs://` URI that may or may not contain path?

**Comment by yan-hic** [comment]
> What is the prescribed way to get a `Bucket` object for a given `gs://` URI that may or may not contain path?

See [here ](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.bucket.Bucket#google_cloud_storage_bucket_Bucket_from_string) - the same method exists for `Bucket`
