### ISSUE TITLE
[Storage] V4 Signature: Formatting Inconsistencies

### ISSUE THREAD

**Issue by frankyn** [googleapis/python-storage#12]
Tracking issue for work defined in companion document.

[New Client Request - GCS SigV4 Formatting Inconsistencies](https://docs.google.com/document/d/11OpYYj2FMFsWe-slIKK-JQC97CUh4CYOWeraR0wuImo).

**Comment by tseaver** [comment]
Working through the spec today:  some bits are overlapped with #9 and @IlyaFaer's PR #48.

**Comment by frankyn** [comment]
Thanks for the update @tseaver. PLMK if there's anything I can help you with.
