### ISSUE TITLE
Support for parallel composite upload

### ISSUE THREAD

**Issue by MasterScrat** [googleapis/python-storage#1202]
The `gcloud` and `gsutil` commands have options to optimize upload speed for large files using parallel composite upload:
https://cloud.google.com/storage/docs/parallel-composite-uploads

It would be beneficial to have an equivalent in `python-storage`.

For context: parallel composite upload splits large files into component pieces, uploads them in parallel and then recomposes them once they're in the cloud (and deletes the temporary components it created locally), using composite objects (https://cloud.google.com/storage/docs/composite-objects).

Note that this is different from this issue: https://github.com/googleapis/python-storage/issues/36, which is about uploading multiple existing files in parallel without splitting them.

Related StackOverflow question: https://stackoverflow.com/questions/55249311/does-gcloud-storage-python-client-api-support-parallel-composite-upload

**Comment by andrewsg** [comment]
As of very recently, we've added a similar feature based on MPU uploads (https://cloud.google.com/storage/docs/multipart-uploads). Please give it a try as `transfer_manager.upload_chunks_concurrently`.
