### ISSUE TITLE
Listing Subdirectories not working with list_blobs and delimiter

### ISSUE THREAD

**Issue by vignesh-arista** [googleapis/python-storage#1208]
I am trying to get all subdirectories within a gcs bucket, but the list is returning empty.
`list_blobs` without the `delimiter` works as expected. I have `objectAdmin` permissions on the bucket

```
from google.cloud import storage
storage_client = storage.Client(project="project_name")
blobs = storage_client.list_blobs(
    "bucket_name", prefix="prefix/", delimiter="/"
)
for prefix in blobs:
    print(prefix)
```
Followed the documentation as given here [https://cloud.google.com/storage/docs/listing-objects#client-libraries](url)

**Comment by cojenco** [comment]
Hi @vignesh-arista could you elaborate more on how your files are structured in the bucket? This will give us a better picture of what you're trying to accomplish. 

Generally speaking, in an Objects:List response there is the [`prefixes` response field](https://cloud.google.com/storage/docs/json_api/v1/objects/list#response) which will be populated when there is a delimiter parameter specified. Try accessing `blobs.prefixes` as shown below: 
```
# Returns objects ordered lexicographically by name
for blob in blobs:
    print(blob.name)

# Returns a blobs.prefixes entity that lists the "subfolders" under the given prefix/
for prefix in blobs.prefixes:
    print(prefix)
```

Find more details in the [list_blobs_with_prefix sample](https://cloud.google.com/storage/docs/samples/storage-list-files-with-prefix?hl=en#storage_list_files_with_prefix-python) and [API documentation](https://cloud.google.com/storage/docs/json_api/v1/objects/list). Hope this helps!

**Comment by vignesh-arista** [comment]
The folder structure looks like this 
```
parent(used as prefix)\
    sub_folder1\
         file1, file2, ....
    sub_folder2\
         file1,file2, ....
```
There are quite a lot of files within each subfolder, so I don't want to iterate through the whole file list. I am looking to get `sub_folder1` and `sub_folder2` as my result.

I am using this script [https://gist.github.com/munro/8256b0c40cee3c929501478f1294e693](url) (a nice workaround) at the moment. 

I tried with `blobs.prefixes` iterator as well, the results were still empty. Sorry for pasting the incorrect code above.

**Comment by cojenco** [comment]
Thanks for the additional information. So it seems like you want to list the folders without scanning the blobs. There is a way to do this in the API, however,  it is not currently supported in the client.

For example, you could run the following curl command:
`curl -X GET 'https://storage.googleapis.com/storage/v1/b/bucket_name/o?delimiter=%2F&fields=prefixes' -H "authorization: Bearer $(gcloud auth print-access-token)"`

Specifying `fields=prefixes` in the API call, you'd receive a response like so:
```
{
    "prefixes": [
        "sub_folder1/",
        "sub_folder2/"
    ]
}
```
Using the client library, you can't avoid calling the iterator, but you should see the list of subfolders in the prefix entity with the following code. We don't yet support this behavior in the client library, but please feel free to file a feature request if you think it would be useful.
```
blobs = storage_client.list_blobs(
    "bucket_name", prefix="prefix/", delimiter="/"
)
list(blobs)

# Returns a blobs.prefixes entity that lists the "subfolders" under the given prefix/
for prefix in blobs.prefixes:
    print(prefix)
```

**Comment by vignesh-arista** [comment]
Thanks for the response 
Using `list(blobs)` worked. This was the part missing in the docs.
