### ISSUE TITLE
Move bucket_bound_hostname code into helper

### ISSUE THREAD

**Issue by IlyaFaer** [googleapis/python-storage#121]
For now we have three places in which we're using `bucket_bound_hostname`. The code is almost the same in all three places, so it'll be good to union it in single helper:
https://github.com/googleapis/python-storage/blob/616f1079e2c8b5a4c900f663a9688da64e2bc1b0/google/cloud/storage/blob.py#L517-L522

https://github.com/googleapis/python-storage/blob/616f1079e2c8b5a4c900f663a9688da64e2bc1b0/google/cloud/storage/bucket.py#L2531-L2536

https://github.com/googleapis/python-storage/blob/616f1079e2c8b5a4c900f663a9688da64e2bc1b0/google/cloud/storage/client.py#L1014-L1020

**Comment by frankyn** [comment]
that sounds good, thanks for catching the improvement.
