### ISSUE TITLE
Blob.from_string() - no error if bucket does not exist

### ISSUE THREAD

**Issue by yan-hic** [googleapis/python-storage#1218]
Debatable if a bug or feature request (through an optional arg ?) but I had expected that the construction fail if the bucket does not exist. That the object may not exist makes sense i.e. you want to upload to a new blob, but I only figured that bucket was the issue when receiving a 404 from the resumable media module.
 
If it makes sense, a check on `bucket.exists()` after that line would be helpful:
https://github.com/googleapis/python-storage/blob/a0416a24c6194850177082bec023346b8acd17a6/google/cloud/storage/blob.py#L413

**Comment by cojenco** [comment]
Hi yan-hic@, thanks for the question. The class method serves as a blob object constructor with a gs:// URI. Similarly as in the constructors, we don't validate whether or not the bucket exists or is valid. We try to avoid client side validations; Instead the library falls back to server side checks and surfaces any error message returned by the server. Hope this helps clarify.

**Comment by yan-hic** [comment]
Thanks @cojenco. I understand the point of view. What about a note/warning about that in the documentation - just to avoid false expectations.

**Comment by cojenco** [comment]
> Thanks @cojenco. I understand the point of view. What about a note/warning about that in the documentation - just to avoid false expectations.

👍 I'll review the documentation and error message around this

**Comment by cojenco** [comment]
Closing this for now. Reviewing our overall documentation, we want to avoid overloading docs and fall back to server side error messages. Open to reopening this with more user signals.
