### ISSUE TITLE
Add http.client.RemoteDisconnected to list of retryable exceptions

### ISSUE THREAD

**Issue by andrewpollock** [googleapis/python-storage#1231]
#### Environment details

  - OS type and version:
  - Python version: `Python 3.11.4`
  - pip version: `pip 23.1.2 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)`
  - `google-cloud-storage` version: `2.14.0`

#### Steps to reproduce

  1. Usage of `Blob.upload_from_filename()` seems to sometimes raise a `RemoteDisconnected` exception
  2. https://docs.python.org/3/library/http.client.html#http.client.RemoteDisconnected get caught by our exception handler (see below)
  3. It doesn't look like https://github.com/googleapis/python-storage/blob/ae9a53b464e7d82c79a019a4111c49a4cdcc3ae0/google/cloud/storage/retry.py#L28-L38 will treat this as retryable?

I think this is in the same vein as #414 and #426

#### Code example

https://github.com/google/osv.dev/blob/b705d0d0b7450ce94137624118a2b54a7f719147/docker/exporter/exporter.py#L57-L64

```python
  def upload_single(self, bucket, source_path, target_path):
    """Upload a single file to a bucket."""
    logging.info('Uploading %s', target_path)
    try:
      blob = bucket.blob(target_path)
      blob.upload_from_filename(source_path)
    except Exception as e:
      logging.error('Failed to export: %s', e)
```

#### Stack trace
```
Failed to export: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by cojenco** [comment]
Discuffed offline and tracked in #1232
