### ISSUE TITLE
Add 503 to list of retriable HTTP response codes

### ISSUE THREAD

**Issue by andrewpollock** [googleapis/python-storage#1232]
### Environment details

  - OS type and version:
  - Python version: `Python 3.11.4`
  - pip version: `pip 23.1.2 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)`
  - `google-cloud-storage` version: `2.14.0`

#### Steps to reproduce

  1. Usage of `Blob.upload_from_filename()` seems to sometimes encounter a 503 response
  2. This seems to result in an immediate failure, despite indications in https://github.com/googleapis/python-storage/blob/ae9a53b464e7d82c79a019a4111c49a4cdcc3ae0/google/cloud/storage/retry.py#L28-L38 that `api_exceptions.ServiceUnavailable` is a 503 and should be retried.

#### Code example

https://github.com/google/osv.dev/blob/b705d0d0b7450ce94137624118a2b54a7f719147/docker/exporter/exporter.py#L57-L64

```python
  def upload_single(self, bucket, source_path, target_path):
    """Upload a single file to a bucket."""
    logging.info('Uploading %s', target_path)
    try:
      blob = bucket.blob(target_path)
      blob.upload_from_filename(source_path)
    except Exception as e:
      logging.error('Failed to export: %s', e)
```

#### Stack trace
```
Failed to export: 503 POST https://storage.googleapis.com/upload/storage/v1/b/osv-test-vulnerabilities/o?uploadType=multipart: {
  "error": {
    "code": 503,
    "message": "We encountered an internal error. Please try again.",
    "errors": [
      {
        "message": "We encountered an internal error. Please try again.",
        "domain": "global",
        "reason": "backendError"
      }
    ]
  }
}
: ('Request failed with status code', 503, 'Expected one of', <HTTPStatus.OK: 200>)
```

Perhaps 503 needs to be added to `_ADDITIONAL_RETRYABLE_STATUS_CODES` also?

**Comment by cojenco** [comment]
As you pointed out, [503](https://github.com/googleapis/google-resumable-media-python/blob/f25e6df2df0a0bf98dd2b08c096aa4b7cc27fe4a/google/resumable_media/common.py#L73) and [connection errors](https://github.com/googleapis/google-resumable-media-python/blob/d7b08b69db70bba237accfe1a672cc2d4c6226e6/google/resumable_media/requests/_request_helpers.py#L38-L50) are considered retryable in the python client. However, retries are only enabled by default for **uploads** if the upload is confirmed to be idempotent - that is by including [request preconditions](https://cloud.google.com/storage/docs/request-preconditions) `if_generation_match` on the upload method call. 

The retry strategy is outlined in https://cloud.google.com/storage/docs/retry-strategy#python. This docs go into detail about which operations are conditionally idempotent, retryable exceptions and client retry config options. Here is a [sample code](https://cloud.google.com/storage/docs/samples/storage-upload-file#storage_upload_file-python) that demonstrates adding the generation match precondition to an upload. 

In your code sample, assuming the upload is for a new file, set `if_generation_match=0`to enable retries; same goes for https://github.com/googleapis/python-storage/issues/1231
```
def upload_single(self, bucket, source_path, target_path):
"""Upload a single file to a bucket."""
logging.info('Uploading %s', target_path)
try:
    blob = bucket.blob(target_path)
    blob.upload_from_filename(source_path, if_generation_match=0)
except Exception as e:
    logging.error('Failed to export: %s', e)
```

**Comment by andrewpollock** [comment]
Hi @cojenco thank you for your fast response.

My reading of https://github.com/googleapis/python-storage/blob/ae9a53b464e7d82c79a019a4111c49a4cdcc3ae0/google/cloud/storage/blob.py#L2827 and the definition of https://github.com/googleapis/python-storage/blob/ae9a53b464e7d82c79a019a4111c49a4cdcc3ae0/google/cloud/storage/retry.py#L141 was that:

1) the default retry behaviour for `upload_from_filename()` is `DEFAULT_RETRY_IF_GENERATION_SPECIFIED`
2) the definition of `DEFAULT_RETRY_IF_GENERATION_SPECIFIED` is the superset of `DEFAULT_RETRY` and a generation precondition being met

Therefore, I am referring to the `DEFAULT_RETRY` behaviour being deficient for the handling of 503s and connection errors.

Have I misunderstood something?

**Comment by cojenco** [comment]
Hi @andrewpollock thanks for the follow-up. 

> 1. the default retry behaviour for upload_from_filename() is DEFAULT_RETRY_IF_GENERATION_SPECIFIED
> 2. the definition of DEFAULT_RETRY_IF_GENERATION_SPECIFIED is the superset of DEFAULT_RETRY and a generation precondition being met

Your understanding in (1) and (2) are accurate. 

However, to clarify your following point: 
> Therefore, I am referring to the DEFAULT_RETRY behaviour being deficient for the handling of 503s and connection errors.

`DEFAULT_RETRY` does handle 503s and connection errors as long as the error is in the retryable excpetions list. As shown below, `DEFAULT_RETRY = retry.Retry(predicate=_should_retry) ` _should_retry predicate will always retry errors that are considered retryable.

https://github.com/googleapis/python-storage/blob/ae9a53b464e7d82c79a019a4111c49a4cdcc3ae0/google/cloud/storage/retry.py#L45-L61


Given your use case has a mix of new and existing objects, a few options worth considering:
(a)  add `if_generation_match` precondition using default retry strategy `DEFAULT_RETRY_IF_GENERATION_SPECIFIED`
```
blob = bucket.blob(target_path)
generation_match = 0
# For existing objects, get the object generation
if blob.exists():
   generation_match = blob.generation
blob.upload_from_filename(source_path, if_generation_match=generation_match)
```

(b) adjust the retry strategy to always retry retryable errors
```
blob.upload_from_filename(source_path, retry=DEFAULT_RETRY)
```

Setting `retry=DEFAULT_RETRY` on the upload method call will trigger an exponential retry for 503s and connection errors; though there is the risk of potential race conditions.

Please let me know if this doesn't answer your question.
