### ISSUE TITLE
Discussion: Contribution Idea - Python Code Sample for Handling Large JSON Files on Google Cloud

### ISSUE THREAD

**Issue by SNEHILUPADHYAY007** [googleapis/python-storage#1236]
Hi Team,

I am currently working on a personal project where I pull data from an API, store it in Cloud Storage, and then load it into BigQuery.

**Problem:** I've encountered an issue where large JSON files are not opening(when opening manually) in most local editors. I've tried using Notepad++ and VSCode.

**Proposed Solution:** 1) To address this issue, I plan to pull data for a limited time frame and store it in a list. Then, I'll create a file which will be of reduced size (because we've pulled limited data only). If additional data remains, I'll pull it again and check if the existing file is of a suitable size. If Yes, I'll append the new data to the existing file and if not create a new file.

2) Also thinking to create the GZIP compressed json file.

I'm adding a rough code that I've written(Not tested as of now). Is this a good approach to create the small json files? Or do you suggest any other ways to address this challenge effectively?
Please suggest :}

Additionally, I would like to kindly ask the assignee to review my proposed solution and provide feedback. If you agree that this approach would be beneficial, would you be open to accepting a pull request to add it to the code sample under cloud storage code samples? Your input and guidance would be greatly appreciated.

![google-trends-data](https://github.com/googleapis/python-storage/assets/31859927/c0869724-f5fe-408f-8800-a0e72cdf12d3)

**Comment by cojenco** [comment]
Hi SNEHILUPADHYAY007@, it appears that you are looking for ways to upload large files using the python storage client. Resumable uploads are the recommended method for uploading large files. Please check out the [resumable upload documentation](https://cloud.google.com/storage/docs/resumable-uploads?hl=en#client-libraries) and [blog post](https://cloud.google.com/blog/topics/developers-practitioners/optimize-cloud-storage-upload-performance-client-libraries) for more details.

If I understand your question correctly, the method [`blob.open()`](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.blob.Blob?hl=en#google_cloud_storage_blob_Blob_open) could be suitable for what you’re trying to do here. `with blob.open()` returns `BlobWriter` which is a [file-like object that writes to a blob](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.fileio.BlobWriter), performing a resumable upload. 

I do not completely follow if your workload specifically requires setting a buffer time and opening large JSON files locally. Is it possible for you to perform a streaming upload while pulling data from the api? 

There are existing code samples with [(1) blob.open](https://github.com/googleapis/python-storage/blob/main/samples/snippets/storage_fileio_pandas.py) and [(2) streaming uploads](https://cloud.google.com/storage/docs/streaming-uploads#client-libraries) that could fit your use case. For instance, below is a sample using blob.open (in conjunction with pandas), and you can continue to write data to the file-like object until it's closed.
```
from google.cloud import storage
import pandas as pd

storage_client = storage.Client()
bucket = storage_client.bucket(bucket_name)
blob = bucket.blob(blob_name)

with blob.open("w") as f:
    df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
    f.write(df.to_csv(index=False))
```

**Comment by SNEHILUPADHYAY007** [comment]
Hi @cojenco,
Good day!!!

I encountered below issue while working with large json files.

--- I successfully uploaded large files to GCS, albeit it took some time. However, upon attempting to open these files locally in various IDEs to view their structure, I encountered freezing and "Not Responding" messages. Upon further investigation, I learned that working with large JSON files can be problematic and that it's preferable to work with smaller files. Consequently, I developed a solution to create smaller JSON files by pulling data for shorter intervals and dynamically checking the file size. If a file already exists with a lesser size(< buffer), I determine whether to append new records to it or create a new file. **However, I'm unsure if this approach is feasible**. Hence, I searched for existing code samples in GCS but found none. I raised an issue thinking that this would work as a good code sample to address because I believe that working with smaller files would be more manageable.

While I managed to upload files, I was unaware of the availability of streaming data upload. I plan to implement this feature.

Your feedback and suggestions on the feasibility of the proposed solution for creating smaller files would be greatly appreciated.

**Comment by cojenco** [comment]
Good day SNEHILUPADHYAY007! Glad to hear that uploads to GCS are working with no issues and streaming uploads fit your use case. It seems like your question is not a storage client library issue, and is more about managing large json files. 

As far as processing large json files efficiently, I’m directing you to the [stackoverflow json discussion](https://stackoverflow.com/questions/tagged/json+python ) which would be more helpful. Generally speaking it’s common to process/stream JSON data in chunks; Better options for performance and memory management, you’ll be able to find more information from the JSON experts. Closing this for now, as it doesn't seem to be an issue with this library. Please reopen if we can help you further.
