### ISSUE TITLE
Support Storage Control Quickstart

### ISSUE THREAD

**Issue by sydney-munro** [googleapis/python-storage#1246]
1. Please update Library Install Section to include install instructions for storage control, if applicable.
2. Please create sample with region tag storage_control_quickstart_sample that shows an example of initializing a storage control client and performing an call.
3. Please include me on reviews for tracking.

See [internal doc](http://goto.google.com/storage-control-quickstart) for further information.

**Comment by cojenco** [comment]
Quickstart PR raised in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11391

**Comment by cojenco** [comment]
@sydney-munro PTAL https://github.com/googleapis/python-storage/pull/1254  ready for review



- [x] Reference Storage Control in this library https://github.com/googleapis/python-storage/pull/1254 
- [x] Storage Control library install instructions included in python mono repo https://github.com/googleapis/google-cloud-python/blob/main/packages/google-cloud-storage-control/README.rst
- [x] Quickstart sample lives at python samples repo https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/storagecontrol/quickstart.py
