### ISSUE TITLE
`Blob.content_type` is `None` when created `from_string()`

### ISSUE THREAD

**Issue by holtskinner** [googleapis/python-storage#1248]
### Example Code

```py
gcs_uri = "gs://github-repo/rag/intro_multimodal_rag/google-10k-sample-14pages.pdf"
gcs_client = storage.Client()
blob = storage.Blob.from_string(gcs_uri, gcs_client)

print(blob.content_type) # Outputs `None`
```

This isn't the case when loading blob from a local file or listing from the bucket.

**Comment by andrewsg** [comment]
This is WAI - the from_string() method intentionally makes no API calls. If we were to modify it to make an API call, it would introduce latency in what should be a pure constructor method like Blob() itself.

To construct the blob and make an API call to fetch metadata, use bucket.get_blob() or just call reload() manually after creation.
