### ISSUE TITLE
Blob Writer's close function causes latency > 15s under load.

### ISSUE THREAD

**Issue by dongzeli95** [googleapis/python-storage#1268]
#### Environment details

  - OS type and version: 
  - `Docker linux`
  - Python version: `python --version`
  - `3.8`
  - pip version: `pip --version`
  - `pip 24.0`
  - `google-cloud-storage` version: `pip show google-cloud-storage`
  - `2.14.0`

#### Steps to reproduce

  1. Use Blob Writer to stream upload audio bytes, as shown below.
  2. Load test it with concurrent requests.

#### Code example

```python
    def get_blob_writer(self, destination_blob_name, content_type='audio/wav') -> BlobWriter:
        blob = self.bucket.blob(destination_blob_name, chunk_size=262144)
        writer = BlobWriter(blob, chunk_size=262144, content_type=content_type, predefined_acl='publicRead')
        return writer

    def __create_on_audio_chunk(self):
        # Create blob writer.
        segment = self.audio_segment
        audio_path = f"{self.audio_path}/{segment}{MP3}"
        stream_writer = GCSClient().get_blob_writer(audio_path, content_type=AUDIO_MP3)

        # Auto increment audio segment idx.
        self.audio_segment += 1

        # Snapshot on_audio_url.
        on_audio_url = self.on_audio_url

        def on_audio_chunk(chunk):
            if stream_writer is None:
                logger.error(f"Stream writer is None, this should not happen: {audio_path}")
                return
            
            try:
                if chunk is END_OF_STREAM:  # Audio End
                    with TimeIt("######## GCP Close stream", 600):
                        stream_writer.close()
                        url = GCSClient().get_url_for_blob(audio_path)
                        if on_audio_url:
                            on_audio_url(url, self.session_id)
                else:
                    stream_writer.write(chunk)
            except BaseException as e:
                capture_exception(f"Error stream upload to GCS: {audio_path}", e)

        return on_audio_chunk
```

#### Stack trace
```
DEBUG:urllib3.connectionpool:https://storage.googleapis.com:443 "POST /upload/storage/v1/b/mockai-dev/o?uploadType=resumable&predefinedAcl=publicRead HTTP/1.1" 200 0
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/plain; charset=utf-8
header: X-GUploader-UploadID: ABPtcPpVZ-tbB7aoNwYpByi2flKfXONcmknAUDjWxfybz3vaJYfic_Xe5kuSvaKDCo6mSN5HTT80BWSa5kcn6_v5xxCgmFWuocFfZz3oj9NX9GCS2w
header: Location: https://storage.googleapis.com/upload/storage/v1/b/mockai-dev/o?uploadType=resumable&predefinedAcl=publicRead&upload_id=ABPtcPpVZ-tbB7aoNwYpByi2flKfXONcmknAUDjWxfybz3vaJYfic_Xe5kuSvaKDCo6mSN5HTT80BWSa5kcn6_v5xxCgmFWuocFfZz3oj9NX9GCS2w
header: Date: Tue, 23 Apr 2024 15:30:21 GMT
header: Vary: Origin
header: Vary: X-Origin
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Pragma: no-cache
header: Content-Length: 0
header: Server: UploadServer
header: Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

######## GCP Close stream took 17.76 seconds
######## GCP Close stream took 17.52 seconds
######## GCP Close stream took 13.67 seconds
```

We are using blob writer to stream upload sequential audio bytes onto a file path. Under load testing for 20 users, the latency becomes huge for blob writer's close function. I am also seeing CPU usage spikes when this happens. Could someone help take a quick look? Thank you!

**Comment by andrewsg** [comment]
The close function will send a media API call (to send buffered data and close up the request) and that API call can be slow in concurrent situations depending on your configuration. What kind of concurrency are you using?

The "transfer_manager.py" module is designed specifically to handle concurrency issues. Buffering user writes and uploading them via Transfer Manager is another option.

**Comment by dongzeli95** [comment]
@andrewsg Thanks for getting back to me. Yes we are using gevent + flask setup for our python service. I think underneath it is using coroutine based concurrency. This is how we initialize the service:
`CMD ["gunicorn", "-k", "geventwebsocket.gunicorn.workers.GeventWebSocketWorker", "-w", "1", "my_app:app", "-b", "0.0.0.0:8080"]`

and we are not using separate threads for this upload jobs.

I do notice the CPU usage spikes up when there are too many concurrent close function calls, it this expected? Curious why the CPU usage is high on the client side, is there any CPU bound logics for this function?

**Comment by andrewsg** [comment]
There is no significant CPU usage that I can think of unless you have enabled checksumming and are using a slow implementation (no sign of that in your code snipped).

However, we don't do testing with gevent, and gevent monkey-patches core libraries in a complex way. Try gunicorn with a process worker and see what happens with the same load. I understand a process worker may not be suitable for your use case but it will help us debug this issue.

**Comment by dongzeli95** [comment]
Yes that's exactly the case, I've changed to:
`CMD ["gunicorn", "-w", "1", "my_app:app", "-b", "0.0.0.0:8080"]`

Under the same load, gevent performs terribly with 100% CPU usages:

<img width="737" alt="Screenshot 2024-04-24 at 4 40 35 PM" src="https://github.com/googleapis/python-storage/assets/55672834/d9917832-ca85-407f-a7f7-9dc3261248ca">

While on regular process worker:
<img width="732" alt="Screenshot 2024-04-24 at 4 28 44 PM" src="https://github.com/googleapis/python-storage/assets/55672834/375ef8bf-42ac-4f6b-a774-4cdbd4b11360">

We have another issue with Speech Recognition SDK with gevent:
https://github.com/googleapis/google-cloud-python/issues/12535

This makes me wonder the decision of using gevent, maybe should consider switching to something else.

**Comment by dongzeli95** [comment]
For a quick workaround, do you think using the [plain REST API](https://cloud.google.com/storage/docs/performing-resumable-uploads#initiate-session) here would help with this issue? Thanks!

**Comment by andrewsg** [comment]
Media operations in the client library are implemented using the requests library, so if you use requests to access the plain REST API to upload data, my first guess would be that CPU usage should be very comparable. Before going all the way to REST I would first try using just a standard upload without BlobWriter just in case there is an avoidable issue with BlobWriter in particular.

I would recommend experimenting with other concurrency options besides gevent, possibly including multiprocessing as one candidate.
