### ISSUE TITLE
Support If*generation preconditions

### ISSUE THREAD

**Issue by frankyn** [googleapis/python-storage#127]
@IlyaFaer has started on this work in the following PR's:
#122 (merged)
#123 (merged)
#130 (merged)
#141 (merged)

* [Bucket Delete](https://cloud.google.com/storage/docs/json_api/v1/buckets/delete): [google.cloud.storage.bucket.Bucket.delete](https://googleapis.dev/python/storage/latest/buckets.html#google.cloud.storage.bucket.Bucket.delete)

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Bucket Get](https://cloud.google.com/storage/docs/json_api/v1/buckets/get): [google.cloud.storage.client.Client.get_bucket](https://googleapis.dev/python/storage/latest/client.html#google.cloud.storage.client.Client.get_bucket)

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Bucket Get](https://cloud.google.com/storage/docs/json_api/v1/buckets/get): [google.cloud.storage.bucket.Bucket.reload](https://googleapis.dev/python/storage/latest/buckets.html#google.cloud.storage.bucket.Bucket.reload)

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Bucket Get](https://cloud.google.com/storage/docs/json_api/v1/buckets/get): [google.cloud.storage.client.Client.lookup_bucket](https://googleapis.dev/python/storage/latest/client.html#google.cloud.storage.client.Client.lookup_bucket)

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Bucket Get](https://cloud.google.com/storage/docs/json_api/v1/buckets/get): [google.cloud.storage.bucket.Bucket.exists](https://googleapis.dev/python/storage/latest/buckets.html#google.cloud.storage.bucket.Bucket.exists)

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Bucket Patch](https://cloud.google.com/storage/docs/json_api/v1/buckets/patch): [google.cloud.storage.bucket.Bucket.patch](https://googleapis.dev/python/storage/latest/buckets.html#google.cloud.storage.bucket.Bucket.patch)

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Bucket Update](https://cloud.google.com/storage/docs/json_api/v1/buckets/update): [google.cloud.storage.bucket.Bucket.update](https://googleapis.dev/python/storage/latest/buckets.html#google.cloud.storage.bucket.Bucket.update)

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Object Copy](https://cloud.google.com/storage/docs/json_api/v1/objects/copy): [google.cloud.storage.bucket.Bucket.copy_blob](https://googleapis.dev/python/storage/latest/buckets.html#google.cloud.storage.bucket.Bucket.copy_blob)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch	

    * ifSourceGenerationMatch

    * ifSourceGenerationNotMatch

    * ifSourceMetagenerationMatch

    * ifSourceMetagenerationNotMatch

* [Object Delete](https://cloud.google.com/storage/docs/json_api/v1/objects/delete): [google.cloud.storage.blob.Blob.delete](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.delete)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Object Delete](https://cloud.google.com/storage/docs/json_api/v1/objects/delete): [google.cloud.storage.bucket.Bucket.delete_blob](https://googleapis.dev/python/storage/latest/buckets.html#google.cloud.storage.bucket.Bucket.delete_blob)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Object Get](https://cloud.google.com/storage/docs/json_api/v1/objects/get): [google.cloud.storage.blob.Blob.reload](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.reload)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Object Get](https://cloud.google.com/storage/docs/json_api/v1/objects/get): [google.cloud.storage.bucket.Bucket.get_blob](https://googleapis.dev/python/storage/latest/buckets.html#google.cloud.storage.bucket.Bucket.get_blob)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Object Get](https://cloud.google.com/storage/docs/json_api/v1/objects/get): [google.cloud.storage.blob.Blob.download_as_string](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.download_as_string)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Object Get](https://cloud.google.com/storage/docs/json_api/v1/objects/get): [google.cloud.storage.blob.Blob.download_to_file](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.download_to_file)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Object Get](https://cloud.google.com/storage/docs/json_api/v1/objects/get): [google.cloud.storage.blob.Blob.download_to_filename](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.download_to_filename)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Object Get](https://cloud.google.com/storage/docs/json_api/v1/objects/get): [google.cloud.storage.blob.Blob.exists](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.exists)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Object Patch](https://cloud.google.com/storage/docs/json_api/v1/objects/patch): [google.cloud.storage.blob.Blob.patch](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.patch)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Object Rewrite](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite): [google.cloud.storage.blob.Blob.rewrite](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.rewrite)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

    * ifSourceGenerationMatch

    * ifSourceGenerationNotMatch

    * ifSourceMetagenerationMatch

    * ifSourceMetagenerationNotMatch

* [Object Rewrite](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite): [google.cloud.storage.blob.Blob.update_storage_class](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.update_storage_class)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

    * ifSourceGenerationMatch

    * ifSourceGenerationNotMatch

    * ifSourceMetagenerationMatch

    * ifSourceMetagenerationNotMatch

* [Object Update](https://cloud.google.com/storage/docs/json_api/v1/objects/update): [google.cloud.storage.blob.Blob.update](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.update)

    * ifGenerationMatch

    * ifGenerationNotMatch

    * ifMetagenerationMatch

    * ifMetagenerationNotMatch

* [Object Compose](https://cloud.google.com/storage/docs/json_api/v1/objects/compose): [google.cloud.storage.blob.Blob.compose](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.compose)

    * ifGenerationMatch

    * ifMetagenerationMatch

    * List of Individual Object

        * "name": string,

        * "objectPreconditions":

            *  "ifGenerationMatch": long

* Object [Copy](https://cloud.google.com/storage/docs/json_api/v1/objects/copy)/[Delete](https://cloud.google.com/storage/docs/json_api/v1/objects/delete): [google.cloud.storage.bucket.Bucket.rename_blob](https://googleapis.dev/python/storage/latest/buckets.html#google.cloud.storage.bucket.Bucket.rename_blob)

    * Copy

        * ifGenerationMatch

        * ifGenerationNotMatch

        * ifMetagenerationMatch

        * ifMetagenerationNotMatch	

        * ifSourceGenerationMatch

        * ifSourceGenerationNotMatch

        * ifSourceMetagenerationMatch

        * ifSourceMetagenerationNotMatch

    * Delete

        * ifGenerationMatch

        * ifGenerationNotMatch

        * ifMetagenerationMatch

        * ifMetagenerationNotMatch

* [Object Delete](https://cloud.google.com/storage/docs/json_api/v1/objects/delete): [google.cloud.storage.bucket.Bucket.delete_blobs](https://googleapis.dev/python/storage/latest/buckets.html#google.cloud.storage.bucket.Bucket.delete_blobs)

    * (List of)

        * ifGenerationMatch

        * ifGenerationNotMatch

        * ifMetagenerationMatch

        * ifMetagenerationNotMatch

**Comment by IlyaFaer** [comment]
The feature was incorporated into all of the listed methods.
