### ISSUE TITLE
project ID error when project explicitly passed.

### ISSUE THREAD

**Issue by wyardley** [googleapis/python-storage#134]
#### Environment details

  - OS type and version: Mac OS X
  - Python version: 3.7.6
  - pip version: 20.0.2
  - `google-cloud-storage` version: 1.28.1

pipenv list from a test venv:

```
(test) lana~/test% pip list
Package                  Version   
------------------------ ----------
cachetools               4.1.0     
certifi                  2020.4.5.1
chardet                  3.0.4     
google-api-core          1.17.0    
google-auth              1.14.1    
google-cloud-core        1.3.0     
google-cloud-storage     1.28.1    
google-resumable-media   0.5.0     
googleapis-common-protos 1.51.0    
idna                     2.9       
pip                      19.2.3    
protobuf                 3.11.3    
pyasn1                   0.4.8     
pyasn1-modules           0.2.8     
pytz                     2020.1    
requests                 2.23.0    
rsa                      4.0       
setuptools               41.2.0    
six                      1.14.0    
urllib3                  1.25.9  
```
#### Steps to reproduce

Normally, I can instantiate a `storage.Client()` object and access a bucket, even without setting a project explicitly, and even when my current default project is different from the project where the bucket lives. However, recently, I've seen some errors doing this, even though I'm sure the credentials are right (as if I set the project explicitly, I can still access the bucket).

  1. Create a clean Python3 environment with pipenv or venv. Either don't have a default project setup via `gcloud`, or be configured with a different project than the bucket lives in (ideally, since bucket names are unique, it would be great if this could just magically work, even if the currently configured project is not where the bucket lives). install latest google-cloud-storage
  2. Call some code, even with the bucket project defined.
`WARNING: No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable`
If project is not set at all, also get:
`OSError: Project was not passed and could not be determined from the environment.`

With my regular setup (even checked all the versions I had installed), I don't get the same error, and can access the bucket just fine, even if I don't explicitly set the project. I have the same versions of google-auth, google-storage, etc. there (also via pip). Happy to provide more details, but would love any suggestions about what might be causing this under certain conditions.

#### Code example

```python
from google.cloud import storage

storage_client = storage.Client(project='buckets-actual-project')
bucket = storage_client.get_bucket('my-bucket')
blobs = bucket.list_blobs()
for blob in blobs:
    ## do some other stuff
```

**Comment by frankyn** [comment]
Hi @wyardley,

Thanks for filing this issue.

I tried do the same and didn't get an error, here's my pip list:

```bash
Package                  Version
------------------------ ----------
cachetools               4.1.0
certifi                  2020.4.5.1
chardet                  3.0.4
google-api-core          1.17.0
google-auth              1.14.1
google-cloud-core        1.3.0
google-cloud-storage     1.28.1
google-resumable-media   0.5.0
googleapis-common-protos 1.51.0
idna                     2.9
pip                      20.1
protobuf                 3.11.3
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pytz                     2020.1
requests                 2.23.0
rsa                      4.0
setuptools               46.1.3
six                      1.14.0
urllib3                  1.25.9
wheel                    0.34.2
```

Could you provide the stack trace returned along with the error you're seeing?

**Comment by wyardley** [comment]
@frankyn thanks! didn't expect that quick a response. My original example isn't as easy to post a traceback of, but now that I'm able to repro this in a more self-contained way, pretty easy to include that:

```
lana~/test% source ./bin/activate
(test) lana~/test% ./test_gcs.py 
<google.oauth2.credentials.Credentials object at 0x10390d990>
/Users/wby/test/lib/python3.7/site-packages/google/auth/_default.py:69: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
Traceback (most recent call last):
  File "./test_gcs.py", line 5, in <module>
    storage_client = storage.Client()
  File "/Users/wby/test/lib/python3.7/site-packages/google/cloud/storage/client.py", line 110, in __init__
    project=project, credentials=credentials, _http=_http
  File "/Users/wby/test/lib/python3.7/site-packages/google/cloud/client.py", line 226, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/Users/wby/test/lib/python3.7/site-packages/google/cloud/client.py", line 181, in __init__
    "Project was not passed and could not be "
OSError: Project was not passed and could not be determined from the environment.
```

**Comment by frankyn** [comment]
Thanks for the follow-up information.

I see the following:

> UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication

You need to use a service account in this case:
https://cloud.google.com/docs/authentication/production

You're using user credentials instead of server credentials.

**Comment by wyardley** [comment]
> You need to use a service account in this case:

In which case, though?
The exact same code works fine with my default credentials on the exact same machine under my regular Python 2 or Python 3 installations.

I get the warning about rate-limiting either way, but it's typically not harmful.

Regular installation:
```
lana~% python3 --version
Python 3.7.6
lana~% pip3 list | grep ^google
google-api-core          1.17.0    
google-api-python-client 1.8.2     
google-auth              1.14.1    
google-auth-httplib2     0.0.3     
google-cloud-core        1.3.0     
google-cloud-dns         0.31.0    
google-cloud-redis       0.3.0     
google-cloud-storage     1.28.1    
google-resumable-media   0.5.0     
googleapis-common-protos 1.51.0    
lana~% cat test_gcs.py 
#!/usr/bin/env python3

from google.cloud import storage

storage_client = storage.Client()
bucket = storage_client.get_bucket('real-bucket-name')
blobs = bucket.list_blobs()
for blob in blobs:
    print(blob.name)
```

In this case (with system pip / Python, not in virtualenv), the objects in the bucket are printed, and there's no fatal error / traceback, even though I get the same warning. Within the venv / pipenv, I get the error /traceback above.

note that if I explicitly force `GOOGLE_CLOUD_PROJECT` or `GCLOUD_PROJECT` to the project name, or pass it into `storage.Client()`,  everything works fine, so I am pretty sure that the credentials themselves are not the issue (I don't have these env vars, or other related ones, explicitly set in my env).

**Comment by frankyn** [comment]
Oh I see, thanks for clarifying. I wonder if this is a bug in the google-auth library then, pulling in @busunkim96 who may have more information. This issue shouldn't impact only google-cloud-storage if it's related to the auth library. 

Does the user credentials you're using have a project value in the file similar to a service account file?

**Comment by wyardley** [comment]
Thanks, yeah, that lib is one area I started looking in earlier.

```
% cat ~/.config/gcloud/application_default_credentials.json
{
  "client_id": "xxx.apps.googleusercontent.com",
  "client_secret": "yyy",
  "refresh_token": "NNN",
  "type": "authorized_user"
}
```

**Comment by wyardley** [comment]
I tried uninstalling / reinstalling all of the python3 Google libs, and removing my entire `~/.config/gcloud` directory and re-authenticating / setting up new default app credentials (also drops some stuff into `legacy_credentials/me@example.com/adc.json` inside the same directory).

If I have this set:
```
lana~% cat ~/.config/gcloud/configurations/config_default
[core]
account = me@example.com
project = different-project
```
then my system Python functions as expected, however, in the venv / pipenv environment it doesn't, even though that environment can read the same files. It seems to be if
`VIRTUAL_ENV` is set, that environment doesn't get looked at (tested this by setting that manually).

**Comment by tseaver** [comment]
I can reproduce this in a shell which doesn't have the `GOOGLE_APPLICATION_CREDENTIALS` envvar pointing to a service account key file:

```bash
$ env | grep GOOGLE || echo No service account
No service account
$ gcloud auth list
                               Credentialed Accounts
ACTIVE  ACCOUNT
...
*       <EMAIL-ADDRESS-WITH-EXPLICIT-OWNERSHIP-OF-BUCKET>
...
$ .nox/system-3-8/bin/pip install --upgrade google-auth
...
Requirement already satisfied: google-auth in ./.nox/system-3-8/lib/python3.8/site-packages (1.30.0)
...
$ cat repro_134.py 
from google.cloud import storage

storage_client = storage.Client(project='<PROJECT-ID-OWNING-BUCKET>')
bucket = storage_client.get_bucket('python-storage-repro-134')
for blob in bucket.list_blobs():
    print(blob.path)
$ .nox/system-3-8/bin/python repro_134.py
/home/tseaver/projects/agendaless/Google/src/python-storage/.nox/system-3-8/lib/python3.8/site-packages/google/auth/_default.py:70: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
Traceback (most recent call last):
  File "repro_134.py", line 4, in <module>
    bucket = storage_client.get_bucket('python-storage-repro-134')
  File "/home/tseaver/projects/agendaless/Google/src/python-storage/google/cloud/storage/client.py", line 402, in get_bucket
    bucket.reload(
...
  File "/home/tseaver/projects/agendaless/Google/src/python-storage/.nox/system-3-8/lib/python3.8/site-packages/google/cloud/_http.py", line 374, in _do_request
    return self.http.request(
  File "/home/tseaver/projects/agendaless/Google/src/python-storage/.nox/system-3-8/lib/python3.8/site-packages/google/auth/transport/requests.py", line 478, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/home/tseaver/projects/agendaless/Google/src/python-storage/.nox/system-3-8/lib/python3.8/site-packages/google/auth/credentials.py", line 133, in before_request
    self.refresh(request)
  File "/home/tseaver/projects/agendaless/Google/src/python-storage/.nox/system-3-8/lib/python3.8/site-packages/google/oauth2/credentials.py", line 228, in refresh
    ) = reauth.refresh_grant(
  File "/home/tseaver/projects/agendaless/Google/src/python-storage/.nox/system-3-8/lib/python3.8/site-packages/google/oauth2/reauth.py", line 338, in refresh_grant
    _client._handle_error_response(response_data)
  File "/home/tseaver/projects/agendaless/Google/src/python-storage/.nox/system-3-8/lib/python3.8/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_data)
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
```

**Comment by apuhegde** [comment]
I'm still getting this issue and it only worked when I followed @wyardley 's hack of explicitly forcing`GOOGLE_CLOUD_PROJECT` to the project name. Was this issue resolved at some point? (For reference I'm using the Apache Airflow (v2.4.1) google provider with python3).

> 
> note that if I explicitly force `GOOGLE_CLOUD_PROJECT` or `GCLOUD_PROJECT` to the project name, or pass it into `storage.Client()`, everything works fine, so I am pretty sure that the credentials themselves are not the issue (I don't have these env vars, or other related ones, explicitly set in my env).
>

**Comment by andrewsg** [comment]
@apuhegde Hi, this issue was supposed to be resolved, but you may be having a related issue or perhaps the resolution wasn't complete as we expected. Could you please open a new issue with substantial details on how you're creating the client within Python and what information you have in your environment variables (just in broad terms of course, not any actual personally identifiable information) so we can investigate?
