### ISSUE TITLE
Google cloud python API returns None for blob.owner attribute

### ISSUE THREAD

**Issue by jorvis** [googleapis/python-storage#136]
I have created a Google bucket with "Fine-grained access control" and a few users have uploaded files to it.  Using the python API I can't seem to get any information on who uploaded each.  The blob.owner property just returns None:

    sclient = storage.Client(project=GCLOUD_PROJECT)
    bucket = storage.bucket.Bucket(client=sclient, name=GCLOUD_BUCKET)
    blob = bucket.get_blob('foo.bar')
    blob.reload()
    print(blob.owner)

I'm calling reload() there because the documentation states it's required to pull some attributes from the server.  All other properties I try print fine (size, updated, etag, md5_hash, etc.).

How can I recover the uploader identification?

#### Environment details

  - OS type and version:  Ubuntu 18.04
  - Python version: 3.7.0
  - pip version: 18.1
  - `google-cloud-storage` version: 1.20.0

#### Steps to reproduce

  1. Place file in google bucket
  2. Attempt to use API to get owner information from the blob

#### Code example

```    sclient = storage.Client(project=GCLOUD_PROJECT)
    bucket = storage.bucket.Bucket(client=sclient, name=GCLOUD_BUCKET)
    blob = bucket.get_blob('foo.bar')
    blob.reload()
    print(blob.owner)
```

#### Stack trace
Doesn't error - just returns None

**Comment by jorvis** [comment]
As a note, I put this on StackOverflow first and another user verified the same problem.

https://stackoverflow.com/questions/61466801/google-cloud-python-api-returns-none-for-blob-owner-attribute?noredirect=1#comment109019518_61466801

**Comment by HemangChothani** [comment]
@jorvis As i found in the [documentation](https://google-cloud-python.readthedocs.io/en/0.32.0/storage/blobs.html#google.cloud.storage.blob.Blob.owner) here, first you need to set the owner locally and then you can retrieve it.

Sample:

    OWNER = {"entity": "project-owner-12345", "entityId": "23456"}
    properties = {"owner": OWNER}
    blob._properties.update(properties)
    blob.patch()
    print (blob.owner)

Else other info about blob you can found through acl.

    print (list(blob.acl))

**Comment by jorvis** [comment]
So if you have 10 people on a gcloud project and each of them can upload to the bucket, there's no way to find out who uploaded to the bucket unless each of them did these steps to set their own owner IDs?

**Comment by HemangChothani** [comment]
Pulling in @frankyn who know more and better about this. Could you please comment on this?

**Comment by frankyn** [comment]
Hi @jorvis, 

Per documentation: https://cloud.google.com/storage/docs/access-control/lists#defaultobjects

```
If you make an authenticated request to upload an object and do not specify any object ACLs when you upload it, then you are listed as the owner of the object and the predefined projectPrivate ACL is applied to the object by default. This means:

You (the person who uploaded the object) are listed as the object owner. Object ownership cannot be changed by modifying ACLs. You can change object ownership only by overwriting an object.

You (the object owner) are granted OWNER permission on the object. If you attempt to give less than OWNER permission to the owner, Cloud Storage automatically escalates the permission to OWNER.

The project owners and project editors group have OWNER permission on the object.

The project team members group has READER permission on the object.
```

Took me a little while to figure out what was going wrong, thank you for your patience.

The issue is `owner` is only populated when `projection=full` but by default `Blob.reload()` uses [`projection=noAcl`](https://github.com/googleapis/python-storage/blob/76bd652a3078d94e03e566b6a387fc488ab26910/google/cloud/storage/_helpers.py#L144) therefore `owner` is not populated. In order to fix this, the library should add a parameter for projection on `Blob.reload()`. @HemangChothani could you take a look at this?

A workaround for this is to use:

```python
from google.cloud import storage
import time

client = storage.Client()

bucket = client.get_bucket("bucket-name")
print(bucket.iam_configuration.uniform_bucket_level_access_enabled)
blob = bucket.blob("assets/test.mp4")
blob.patch() # nothing is updated but uses `projection=full`
print(blob.owner)
```

**Comment by jorvis** [comment]
Thanks all!
