### ISSUE TITLE
Resumable media retry appears to treat `deadline` differently than google.api.core.Retry 

### ISSUE THREAD

**Issue by samlevy3** [googleapis/python-storage#1361]
#### Environment details

  - Python version: 3.11.10
  - pip version: 24.2
  - `google-cloud-storage` version: 2.18.2

#### Description 
For resumable media calls in cloud storage (ex: [download_as_string](https://github.com/googleapis/python-storage/blob/main/google/cloud/storage/blob.py#L1009)), the provided `google.api.core.Retry` is [converted](https://github.com/googleapis/python-storage/blob/main/google/cloud/storage/_helpers.py#L634) to a `google.resumable_media.RetryStrategy`. However, the meaning of the provided `deadline` appears to differ between these two classes. 

For `google.api.core.Retry`, `deadline` seems to be defined as ["the maximum amount of time a function can block"](https://googleapis.dev/python/google-api-core/2.2.2/_modules/google/api_core/retry.html#:~:text=The%20deadline%20is%20the%20maxmimum%20amount%0Aof%20time%20a%20method%20can%20block.) 

However, for `google.resumable_media.RetryStrategy`, `max_cumulative_retry` (what `deadline` corresponds to) is defined as ["The maximum total amount of time to sleep during the retry process." ](https://github.com/googleapis/google-resumable-media-python/blob/main/google/resumable_media/common.py#L124C49-L125C48)

There appears to be a mismatch between the definitions though. One refers to the total time the function blocks while the other refers to the cumulative time spent sleeping between retries. 

If this is indeed a mismatch is it possible to update the documentation of resumable media operations to clarify that they have a different retry strategy?

**Comment by andrewsg** [comment]
There is a mismatch. We intend to unify the two retry strategies either during the next major version release or in a feature release soon after that. In the meantime we'll see if we can make tweaks to the two strategies to bring them closer together.

**Comment by samlevy3** [comment]
Thanks for the reply @andrewsg! Do you have information about what unification will look like? Will the `google.resumable_media.RetryStrategy` be changed to match the `google.api.core.Retry`?

**Comment by andrewsg** [comment]
I would like it if it would turn out like that, but the resumable media retry system is _much_ more complicated than the standard retry system, as it counts bytes written to stream and resumes from there whenever possible, so given that it's not fully designed yet I can't guarantee the outcome. Unification might look like standardizing on `google.api.core.Retry`, or it might look like something purpose-built that is backwards compatible with those `Retry` objects.

**Comment by samlevy3** [comment]
Understood. I will keep an eye on it and adjust if necessary based on the outcome! Thanks for the clarification!

**Comment by andrewsg** [comment]
This will be fixed in the new major version update, unifying retries around the `google.api.core.Retry` system.
