### ISSUE TITLE
Storage list_blobs iterator doesn't return prefixes

### ISSUE THREAD

**Issue by andtrott** [googleapis/python-storage#1388]
Title: list_blobs() iterator.prefixes returns empty when API response contains prefixes

## Issue Description
When using `list_blobs()` with a prefix and delimiter to list "directories" in a GCS bucket, the `.prefixes` property of the returned iterator is empty even though the raw API response shows that prefixes exist.

## Reproduction Steps
Here's a complete example using the public bucket `gcp-public-data-landsat`:

```python
from google.cloud import storage
import logging

# Set up logging to see API responses
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

# Initialize client and bucket
client = storage.Client()
bucket = client.bucket('gcp-public-data-landsat')

prefix = "LC08/"  # This prefix exists in the landsat bucket
delimiter = "/"

# First show that the raw API response contains prefixes
logger.debug("\nChecking raw API response:")
page = bucket.list_blobs(prefix=prefix, delimiter=delimiter)._get_next_page_response()
logger.debug(f"Raw API response: {page}")  # Shows prefixes exist

# Now demonstrate that iterator.prefixes is empty
logger.debug("\nTrying to iterate prefixes:")
iterator = bucket.list_blobs(prefix=prefix, delimiter=delimiter)
prefix_count = 0
for prefix in iterator.prefixes:
    prefix_count += 1
    logger.debug(f"Found prefix: {prefix}")
logger.debug(f"Total prefixes found: {prefix_count}")  # Shows 0

# Also demonstrate list() returns empty
prefixes = list(iterator.prefixes)
logger.debug(f"List of prefixes: {prefixes}")  # Shows []

```

## Expected Behavior

The iterator's .prefixes property should provide access to the prefixes returned in the API response
Both iterating through iterator.prefixes and calling list(iterator.prefixes) should return the prefixes

## Actual Behavior

The raw API response shows prefixes exist: {'kind': 'storage#objects', 'prefixes': [...]}
However, iterator.prefixes appears empty when iterated
list(iterator.prefixes) returns an empty list

## Workaround
Currently using direct access to the API response as a workaround:
pythonCopypage = bucket.list_blobs(prefix=prefix, delimiter=delimiter)._get_next_page_response()
prefixes = page.get('prefixes', [])

## Environment

google-cloud-storage version: 2.18.2
Python version: Python 3.11.6
OS: Darwin 23.6.0

Related Issues

#436
#483

This issue was co-authored by Claude.

**Comment by cojenco** [comment]
Hi andtrott@ thanks for the question. The iterator has to be called first in order to access the list of prefixes. Try adding a `list(iterator)`to consume the iterator first

```
iterator = bucket.list_blobs(prefix=prefix, delimiter=delimiter)
list(iterator)
...
prefix_count = 0
for prefix in iterator.prefixes:
```

See the [list_files_with_prefix example](https://cloud.google.com/storage/docs/samples/storage-list-files-with-prefix?hl=en#storage_list_files_with_prefix-python) with detailed explanation

See related issues
https://github.com/googleapis/python-storage/issues/1208#issuecomment-1881644842
https://github.com/googleapis/python-storage/issues/863#issuecomment-1245740122

**Comment by andtrott** [comment]
Thanks for the response! Stand by the expected behavior, but that's a good workaround - thanks!
