### ISSUE TITLE
Python Client Not Working on KFP

### ISSUE THREAD

**Issue by WillianFuks** [googleapis/python-storage#175]
Hello,

I just created an [Issue](https://github.com/kubeflow/kubeflow/issues/5063) on the kubeflow repository but I was wondering if the team responsible for the Python Client could help us out as well as this seems to be something related to how the client builds the credentials.

As it seems, inside the pipelines API something goes wrong with the authentication and the result is an anonymous client. All steps to replicate the issue was reported in the previous link.

Thanks in advance,

**Comment by frankyn** [comment]
Followed up through the linked github Issue.

**Comment by frankyn** [comment]
Issue resolved in linked issue. Closing this issue.
