### ISSUE TITLE
Changes made in jupyter notebook ipynb file are not uploaded to the bucket

### ISSUE THREAD

**Issue by limbuu** [googleapis/python-storage#2]
We upload  jupyter notebook .ipynb file in google bucket. Whenever we make changes and upload the same file the changes are not being uploaded in the bucket. Looks like there is cache issue while uploading/patching  the changed file. How to fix the issue??
We use the following code:
  
```
    def upload_blob(self, file_to_upload):
        """ Uploads file to the bucket"""
        blob = self.bucket.blob(file_to_upload)
        blob.upload_from_file(file_to_upload)
        print('File {} uploaded to {}'.format(file_to_upload, file_to_upload))
```

**Comment by HemangChothani** [comment]
@limbuu  Any update on this issue?

**Comment by HemangChothani** [comment]
@limbuu Any update?

**Comment by limbuu** [comment]
sorry @HemangChothani was not working in this issue for a while, tried the snippet, it hasn't worked so far.

**Comment by tseaver** [comment]
@limbuu [`Blob.upload_from_file`](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.upload_from_file) expects to be passed a file-like object, not a filename.  Please use `Blob.upload_from_filename` instead.
