### ISSUE TITLE
download_to_filename failing 

### ISSUE THREAD

**Issue by sumanthssr** [googleapis/python-storage#200]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-python/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version
3. Python version and virtual environment information: `python --version`
4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`

#### Steps to reproduce

  1. ?

#### Code example

```python
# example
```

#### Stack trace
```
Storage pull failedTraceback (most recent call last):
  File "/opt/conda/envs/aalatest2/lib/python3.6/site-packages/o9storage/gcs_storage.py", line 67, in storage_pull
    blob.download_to_filename(archive_path)
  File "/opt/conda/envs/aalatest2/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 703, in download_to_filename
    self.download_to_file(file_obj, client=client, start=start, end=end)
  File "/opt/conda/envs/aalatest2/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 675, in download_to_file
    self._do_download(transport, file_obj, download_url, headers, start, end)
  File "/opt/conda/envs/aalatest2/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 613, in _do_download
    download.consume(transport)
  File "/opt/conda/envs/aalatest2/lib/python3.6/site-packages/google/resumable_media/requests/download.py", line 174, in consume
    self._write_to_stream(result)
  File "/opt/conda/envs/aalatest2/lib/python3.6/site-packages/google/resumable_media/requests/download.py", line 117, in _write_to_stream
    with response:
AttributeError: __enter__
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by HemangChothani** [comment]
@sumanthssr Could please provide the reproducible code and environment details:

Following code and environment which works for me:

**Code example:**
```python
from google.cloud import storage 

client = storage.Client()
bucket = client.get_bucket('bucket-name')
blob = bucket.get_blob('blob-name')
blob.download_to_filename('path/to/download')
```
**Environment Details:**

    google-api-core==1.21.0
    google-auth==1.18.0
    google-cloud-core==1.3.0
    google-cloud-storage==1.29.0
    google-resumable-media==0.5.1
    requests==2.24.0
    urllib3==1.25.9

**Comment by tseaver** [comment]
@sumanthssr Your version if the `requests` library is waaaay out of date:  `response` objects added context manager support in [`requests-2.18.0`](https://requests.readthedocs.io/en/master/community/updates/#id13), released 2017-06-14.  That is the minimum version of `requests` which is compatible with current versions of `google-resumable-media` (since version `0.3.0`) and `google-cloud-storage` (since at least version `1.6.0`).
