### ISSUE TITLE
blob.upload_from_filename returns error if pathlib.Path is given instead of str

### ISSUE THREAD

**Issue by takotab** [googleapis/python-storage#205]
Please be aware that an error is given when you use pathlib.Path as filelocation instead of a str. It will say that it could not be converted into unicode.

Would be nice to either get a message saying that you should insert a str or transform the Path to str to prevent the error.

Thanks

**Comment by HemangChothani** [comment]
@takotab I thnik you are using python2 because it's working fine with python3 or could please share your environment details.


Example:
```python
from pathlib import Path
from google.cloud import storage

client = storage.Client()
bucket = client.get_bucket('bucket-name')
b = bucket.blob('new-blob')
in_file_1 = Path('/filepath')
b.upload_from_filename(in_file_1)

**Comment by takotab** [comment]
Ahh I see, I have some boiler plate code that tries to make a blob from a Path:

```
from pathlib import Path
from google.cloud import storage

client = storage.Client()
bucket = client.get_bucket('bucket-name')
in_file_1 = Path('/filepath')
b = bucket.blob(in_file_1)
b.upload_from_filename(in_file_1)
```
then it returns:
```
----> 9 b = bucket.blob(in_file_1)

....

ValueError: Path('/filepath') could not be converted to unicode
```

I stand corrected. Maybe still worth giving an bit of guides in the error message, but that's up to you.

**Comment by HemangChothani** [comment]
@takotab We have used a method which declared in `google-cloud-core` library and that function is used by many other libraries too, so i think it's not feasible to change the message for specific thing and they tried to give straight and meaningful message as much as possible.
