### ISSUE TITLE
Storage: wait option for delete_blobs method

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googleapis/python-storage#22]
#### Environment details
latest

#### Steps to reproduce
```python
blobs = [1000000 blobs]
slow_create_blobs(blobs)
delete_blobs(blobs)
slow_create_blobs(blobs)
assert count_blobs(blobs) = big_number
```
An unpredictable result depends on delete_blobs how fast it is versus the slow_create_blobs

**Comment by IlyaFaer** [comment]
@VelizarVESSELINOV, code snippet in this issue doesn't give much of info, but I think, you're using `Bucket.delete_blobs()` method. If so, it doesn't seem that "wait" option is needed. According to [Storage docs](https://cloud.google.com/storage/docs/consistency), object deletion is strong consistent. That means, if you called `objects.delete` method and it returned empty result, than object is already deleted from Storage (see the [method docs](https://cloud.google.com/storage/docs/json_api/v1/objects/delete)). In other words, you don't need a "wait" option, as `delete_blobs()` will return only when all specified blobs will be truly deleted. Thus, it's already waiting.

Closing this issue. Feel free to reopen, if you have any concerns/propositions.
