### ISSUE TITLE
consume() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by chmoder** [googleapis/python-storage#220]
When using blob.download_as_string, it includes a kwarg called `timeout`.  This is raising an exception that `consume() got an unexpected keyword argument 'timeout'`

It looks like a similar issue is known in [google-resumable-media-python](https://github.com/googleapis/google-resumable-media-python/issues/148).

#### Environment details

  - OS type and version: Google App Engine Standard Second Generation Python 3.7
  - Python version:  3.7
  - pip version: ?
  - `google-cloud-storage` version: 1.30.0

#### Steps to reproduce

  1. `download_as_string(**kwargs)`

#### Code example

```python
from google.cloud import storage


def download_blob(bucket_name, source_blob_name):
    """Downloads a blob from the bucket."""
    # bucket_name = "your-bucket-name"
    # source_blob_name = "storage-object-name"
    # destination_string = None

    storage_client = storage.Client()

    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(source_blob_name)
    destination_string = blob.download_as_string()

    print(destination_string)
```

#### Stack trace
```
"Traceback (most recent call last):
  File "/srv/controllers/e_app/carriers/abstract_carrier/interfaces/carrier_enrollment_application_interface.py", line 873, in __prepare_payload
    payload_container = self.product.transform_enrollment_application()
  File "/srv/controllers/e_app/carriers/abstract_carrier/abstract_product.py", line 113, in transform_enrollment_application
    payload_container = self.exporter.generate_payload()
  File "/srv/controllers/e_app/carriers/montana_health_co_op/exporter/exporter.py", line 33, in generate_payload
    MHCRequestBody(self._carrier_instance)
  File "/srv/controllers/e_app/carriers/montana_health_co_op/exporter/request.py", line 48, in __init__
    'pdf': self.app_pdf,
  File "/srv/controllers/e_app/carriers/montana_health_co_op/exporter/request.py", line 34, in app_pdf
    pdf = self.carrier_instance.generate_enrollment_application_pdf(app_id_range='app')
  File "/srv/controllers/e_app/carriers/abstract_carrier/interfaces/carrier_enrollment_application_interface.py", line 599, in generate_enrollment_application_pdf
    wet_sign_override=wet_sign_override
  File "/srv/models/eapp/enrollment_application.py", line 318, in generate_applicant_pdf
    source_pdf = carrier_product_form.get_fillable_pdf()
  File "/srv/models/eapp/carrier_product_form.py", line 223, in get_fillable_pdf
    cloud_document_file_stream = CloudModule().fetch_cloud_document(self.cloud_fillable_app_key)
  File "/srv/controllers/cloud_storage/cloud_module.py", line 127, in fetch_cloud_document
    blob_string = cloud_storage_client.get_gcs_blob(uri=file_path)
  File "/env/lib/python3.7/site-packages/csg/storage/client.py", line 72, in get_gcs_blob
    blob_contents = blob.download_as_string()
  File "/env/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1179, in download_as_string
    timeout=timeout,
  File "/env/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1005, in download_to_file
    timeout=timeout,
  File "/env/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 872, in _do_download
    response = download.consume(transport, timeout=timeout)
TypeError: consume() got an unexpected keyword argument 'timeout'" 
```

**Comment by busunkim96** [comment]
@chmoder Could you let us know which version of `google-resumable-media` you are using?

**Comment by chmoder** [comment]
> @chmoder Could you let us know which version of `google-resumable-media` you are using?

google-resumable-media       0.7.0

**Comment by chmoder** [comment]
We discovered that overriding the version to `google-resumable-media 0.6.0` in requirements.txt is a workaround.

**Comment by frankyn** [comment]
Hi @chmoder, thanks for the additional information.

I tried to reproduce the error you're seeing but haven't been successful.

Could you try the following:

1. `pip install virtualenv`
1. `virtualenv repro_env`
1. `source repro_env/bin/activate`
1. `pip install google-resumable-media==0.7.0`
1. `pip install google-cloud-storage=1.30.0`


In your follow-up post could you share the following:

1. Share the example you're using to reproduce the issue.
1. Include virtualenv dependency versions using `pip freeze` as well.

Thank you for your patience.

**Comment by chmoder** [comment]
I just wanted to get back to you one this.  I can't seem to reliably reproduce the issue.  Sometimes we get the error, other times not.  But at the moment, it is looking more like a build system, or caching, situation with app engine than package bug. 

If you can wait till next Tuesday to close this, we will have more real world experience to verify our theory.

**Comment by frankyn** [comment]
Thanks @chmoder, 

1. Which App Engine are you using? (Standard or Flexible)
2. Do you only see this issue when deploying to App Engine?

I'll wait on closing this off until next Tuesday as well.

**Comment by chmoder** [comment]
1) App Engine standard second generation python 3.7
2) Yes it has happened 3 out of 6 times. 

Yesterday we deployed with a cache refresh and this error did not happen.  We are doing a full code release on Monday, so we hope things go smoothly and are confident enough to close this after that.

**Comment by chmoder** [comment]
We have been running on google-cloud-storage version: 1.30.0 for a while now without any errors, so thanks for the help and sorry for the non-issue.
