### ISSUE TITLE
SignatureDoesNotMatch when accessing a signed url after creating file with encryption_key

### ISSUE THREAD

**Issue by priyanshujain** [googleapis/python-storage#221]
I am creating signed URL using 

```py
class GoogleCloudStorage(object):
    def __init__(self):
        self._client = storage.Client(
            project=settings.GS_CREDENTIALS.project_id, credentials=settings.GS_CREDENTIALS
        )
        self._bucket = self._client.bucket(settings.GS_BUCKET_NAME)

    def create_blob(self, filename, encryption_key):
        encryption_key = base64.b64decode(encryption_key)
        blob = self._bucket.blob(filename, encryption_key=encryption_key)
        return blob

    def get_blob(self, file_path, encryption_key):
        encryption_key = base64.b64decode(encryption_key)
        blob = self._bucket.get_blob(file_path, encryption_key=encryption_key)
        return blob

    def upload_from_file(self, file_obj, filename, content_type, encryption_key):
        """
        Uploads a file to a given Cloud Storage bucket.
        """
        blob = self.create_blob(filename, encryption_key=encryption_key)
        blob.upload_from_file(file_obj=file_obj, content_type=content_type)
        return True

    def upload_from_string(self, file_content, filename, content_type, encryption_key):
        """
        Uploads a file to a given Cloud Storage bucket.
        """
        blob = self.create_blob(filename, encryption_key=encryption_key)
        blob.upload_from_string(file_content, content_type=content_type)
        return True

    def get_file(self, file_path, encryption_key):
        """
        returns the public url to the requested object.
        """
        blob = self.get_blob(file_path, encryption_key=encryption_key)
        expiration = timedelta(minutes=30)
        url = blob.generate_signed_url(method="GET", expiration=expiration)

        if isinstance(url, six.binary_type):
            url = url.decode("utf-8")
        return url
```

Upload file is working fine but when I try to get the file with signed URL I am getting this error

```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message>
<StringToSign>GET 1596045345 /spotlight-stag/COVReport_Final_20200320-2020-07-29-165239-defd0fdbe121411b8a3a419f87c5594b.pdf</StringToSign>
</Error>
```

EDIT:

This works fine if I don't use `encryption_key `. But I am seeking for a solution that can work with `encryption_key `.
Thanks.

**Comment by priyanshujain** [comment]
@HemangChothani @frankyn Can you help me solve this `encryption_key` problem? 

Thanks in advance.

**Comment by HemangChothani** [comment]
@priyanshujain The sample code will help you to resolve the issue:

```python
import base64
import hashlib
import requests

from google.cloud import storage

client = storage.Client()
bucket = client.get_bucket('bucket_name')
blob = bucket.get_blob('blob_name',encryption_key=encryption_key)
sign_url = blob.generate_signed_url(expiration=expiration)

headers = {} 
headers["x-goog-encryption-algorithm"] = "AES256"
encoded_key = base64.b64encode(encryption_key).decode("utf-8")
headers["x-goog-encryption-key"] = encoded_key
key_hash = hashlib.sha256(encryption_key).digest()
key_hash = base64.b64encode(key_hash).decode("utf-8")
headers["x-goog-encryption-key-sha256"] = key_hash

response = requests.get(sign_url, headers=headers) 
print(response.status_code)
print(response.text)

**Comment by HemangChothani** [comment]
@priyanshujain Did the above example help you to resolve the issue?

**Comment by priyanshujain** [comment]
@HemangChothani  Thanks for providing help in this. My main idea behind using `encryption_key` is to not allow someone to access files directly for GCS bucket. But according to your example, I need to pass `encryption_key` to end-user. 

Is there any way I can generate a public signed URL with `encryption_key` and GCS blob combined?

**Comment by frankyn** [comment]
Hi @priyanshujain,

When using customer supplied encryption keys with Signed URLs, you'll need to pass the encryption key in request headers. There's no way around it in this case because Cloud Storage uses the header information to decrypt the object during the request before returning it to the user. CSEK key material isn't stored server side and requires that requester's send it in the request. 

An alternative would be locking down object viewer permission only to the service account used to create the Signed URL. Only the Project Administrator and Service account have permission to view objects. 

IIUC, you're trying to avoid the possibility of allowing Project Administrators from viewing object information. Is that right?

**Comment by HemangChothani** [comment]
@priyanshujain Did frank's answer help you?

**Comment by priyanshujain** [comment]
@frankyn @HemangChothani  Sorry for the late response. Thanks for explaining the decryption process using request headers, but as you predicted correctly my use case is to protect files from GCP project admins from viewing the object so that no one person has right to view the object and it can only be viewed as a combination of some key in DB and file in GCS without. 

If there is any workaround this please let me know, or else we can close the issue. Thank you both for helping me out.

**Comment by frankyn** [comment]
Closing out, an end-user does require both encryption keys and signed URL to download an object. Encryption key can't be placed into the signed URL and would require an additional layer of implementation to resolve.

Thanks for raising the question! Cheers.
