### ISSUE TITLE
Error when updating blob

### ISSUE THREAD

**Issue by DylanBowden** [googleapis/python-storage#223]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-storage/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Ubuntu 19.10
  - Python version: `python --version` 3.7.5
  - pip version: `pip --version` pip 20.2
  - `google-cloud-storage` version: `pip show google-cloud-storage` 1.30.0

#### Steps to reproduce

  1. Add google-cloud-storage in requirements.txt without explicit version -> this will download 1.30
  2.  Create a blob in a bucket
  3. Update the blob in the bucket using either `upload_from_filename` or `upload_from_file`
  4. Receive a 400 error
  5. Downgrade to previous version to fix issue

#### Code example

```python
blob = bucket.blob('my_existing_filename')
blob.upload_from_filename(file_local_path)

```

#### Stack trace
```
Traceback (most recent call last):
  File "main.py", line 37....
  ......
  File "...../python/venv/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1925, in upload_from_file
    _raise_from_invalid_response(exc)
  File "......./python/venv/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 3262, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.BadRequest: 400 PUT https://storage.googleapis.com/upload/storage/v1/b/......./o?uploadType=resumable&upload_id=AAANsUn8LbnT7zo_tanJo2UoUxUyz1f5JztY96v1hOwyDWvlbTLltuxrYdEbXEOG28c7B4sis32UUALPkOhNhTUGV7giAGisEg: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>, 308)


```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by HemangChothani** [comment]
@DylanBowden I tried to reproduce the error you're seeing but haven't been successful.

Could you try the following with the fresh virtual environment :
1.    pip install virtualenv
2.    virtualenv my_env
3.    source my_env/bin/activate
4.    pip install google-resumable-media==0.7.0
5.    pip install google-cloud-storage=1.30.0
6.    Run your example code

OR

-   Share the example you're using to reproduce the issue.
-   Add the Python version you're using.
-   Add virtualenv dependency versions using `pip freeze` as well.

**Comment by HemangChothani** [comment]
@DylanBowden  Any update from your side?

**Comment by HemangChothani** [comment]
Please follow-up / reopen if you can provide more information.
