### ISSUE TITLE
Storage: Capture relevant headers to blob properties during download

### ISSUE THREAD

**Issue by tseaver** [googleapis/python-storage#24]
Residual from googleapis/google-cloud-python#9003.

@william-silversmith notes that even with `raw_download` enabled, he is unable to detect the `content_type` of a downloaded blob without performing an additional `reload` request, which is prohibitive for his usecase at scale.  E.g.:

```python
blob = bucket.blob( key )
binary = blob.download_as_string(raw_download=True)
if blob.content_encoding == 'gzip':
    return gunzip(binary)
elif blob.content_encoding == 'br':
    return brotli.decompress(binary)
else:
    return binary
```
Potentially even...

```python
if blob.content_type == 'application/json':
    return json.loads(binary.decode('utf8'))
```

**Comment by william-silversmith** [comment]
Hi Tres, I've made some changes to my own branch of this repo and they seem to work. I tried making a PR but the button was greyed out. Here's a link to the changes in case y'all are interested. In the mean time, I'll direct my repos to use the forked version.

https://github.com/googleapis/python-storage/compare/master...seung-lab:master

**Comment by william-silversmith** [comment]
Unfortunately, it seems PyPI won't let me use a direct reference to github. It would be extremely convenient if some version of this could get merged.

**Comment by william-silversmith** [comment]
Figured out the PR submission issue.
