### ISSUE TITLE
Check if blob exists without reading the file

### ISSUE THREAD

**Issue by s2t2** [googleapis/python-storage#243]
**Is your feature request related to a problem? Please describe.**

Sometimes when I'm using `blob.exists()` to check if a file exists, it will time out. It seems to happen more often with larger files.

 **Describe the solution you'd like**

I'd like to be able to quickly and reliably check whether the file exists, without regard to the file size.

I assume this part of the underlying code actually downloads the file, or am I misunderstanding the role of the `_target_object` param?

```py
client._connection.api_request(
                method="GET",
                path=self.path,
                query_params=query_params,
                _target_object=None,
                timeout=timeout,
            )
```

 **Describe alternatives you've considered**

I checked the [docs](https://googleapis.dev/python/storage/latest/_modules/google/cloud/storage/blob.html#Blob.exists), could maybe set a different timeout threshold, but would that be more reliable? 

 **Additional context**

**Comment by tseaver** [comment]
`Blob.exists` makes the API request using the query string `?fields=name`, which means the size of the object won't affect the response time.  The `_target_object` bit allows the blob's metadata to be updated with the response (e.g., ETag, etc.) -- it doesn't handle the actual content (which won't be returned, anyway).

Passing a longer timeout should reduce the incidence of timeouts.
