### ISSUE TITLE
Error processing line 3 of google_cloud_storage-1.30.0-py3.8-nspkg.pth

### ISSUE THREAD

**Issue by danieldhz** [googleapis/python-storage#252]
Hi There,

Upon my installation of google libs. I get the following error in my virtualenv:
```

Error processing line 3 of C:\google_cloud_storage-1.30.0-py3.8-nspkg.pth:
Remainder of file ignored
Error processing line 3 of C:\StartUp\IdeaStage\Tier 1\Alexa smart timer\AlexaLibs\lib\site-packages\google_cloud_storage-1.30.0-py3.8-nspkg.pth:
  Traceback (most recent call last):
    File "c:\python38\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 553, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'
```
I'd like to know what I shall do?

**Comment by HemangChothani** [comment]
@danieldhz  Delete this file `C:\StartUp\IdeaStage\Tier 1\Alexa smart timer\AlexaLibs\lib\site-packages\google_cloud_storage-1.30.0-py3.8-nspkg.pth` and try again to install it. 
OR
edit the .pth file (immediately after the text Error processing line 3) and added a newline character after the first semicolon and also try with third one.

- If it doesn't help then please share reproducible steps or code.

**Comment by danieldhz** [comment]
@HemangChothani Thanks for your answer. The error did get removed upon deleting it. However, I now face the same error as previous when deploying the venv to AWS`"Unable to import module 'lambda_function': No module named 'google.cloud'"`

**Comment by HemangChothani** [comment]
@danieldhz  I am not very much familiar with aws lambda, but i would like to suggest few things:

- Install the library like `pip install google-cloud-storage -t  and other dependencies.
- need to export  the .../site-packages to aws lambda to your deployment path

For more details you can follow these steps listed [here](https://stackoverflow.com/questions/52913257/google-cloud-platform-api-for-python-and-aws-lambda-incompatibility-cannot-impo/52913258#52913258) , i think it would be more helpful to you


I think you have followed https://docs.aws.amazon.com/lambda/latest/dg/python-package.html document and use `With a virtual environment` for deployment.

OR

 Please show in detail the steps you used to get google-cloud-storage and its dependencies installed into the environment.

**Comment by danieldhz** [comment]
@HemangChothani Hi Hemang!

**Comment by danieldhz** [comment]
it now says `No module named 'google.cloud'` despite the dependencies not changing

**Comment by HemangChothani** [comment]
Use this command :  ` pip install --user  --upgrade google-cloud-storage`.
If it still doesn't work then do `pip freeze` in you environment  and share it.

**Comment by HemangChothani** [comment]
@danieldhz Any update?

**Comment by danieldhz** [comment]
@HemangChothani Sorry for not getting back. I realized that not all of the libs were being uploaded to layers as it maxed out incapacity.

**Comment by HemangChothani** [comment]
@danieldhz Closing this issue, feel free to reopen if the error occurs again.
