### ISSUE TITLE
urllib3.connectionpool:Connection pool is full, discarding connection: storage.googleapis.com

### ISSUE THREAD

**Issue by SaschaHeyer** [googleapis/python-storage#253]
#### Environment details

  - OS type and version: Google Cloud Platform AI Platform Job
  - Python version: tensorflow/tensorflow:2.0.0-py3
  - pip version: tensorflow/tensorflow:2.0.0-py3
  - google-cloud-storage version: google-cloud-storage==1.28.1

#### Steps to reproduce

  1. Run multiple downloads in parallel

#### Code example
/

#### Stack trace
```
urllib3.connectionpool:Connection pool is full, discarding connection: storage.googleapis.com
```
Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by HemangChothani** [comment]
@SaschaHeyer I think this is because of the urllib3's default `pool_maxsize` which is 10, so you can edit that size and increase it and by default `pool_block` is `False` so make it `True`,  that will be helpful.

**Comment by HemangChothani** [comment]
**Here is the sample:** 

from google.cloud import storage
import requests

GCS_CLIENT = storage.Client()
adapter = requests.adapters.HTTPAdapter(pool_connections=128, pool_maxsize=128, max_retries=3, pool_block=True)
GCS_CLIENT._http.mount("https://", adapter)
GCS_CLIENT._http._auth_request.session.mount("https://", adapter)

**Comment by frankyn** [comment]
Hi @SaschaHeyer, 

Did @HemangChothani answer your question?

**Comment by HemangChothani** [comment]
Please follow-up / reopen if you can provide more information.
