### ISSUE TITLE
Unable to install it on Nvidia Jetson Nano

### ISSUE THREAD

**Issue by Pradyumn10** [googleapis/python-storage#254]
Whenever I am installing this , it gives me error: "command aarch-64-linux-gnu-gcc" failed with exit status one. I want to use google-cloud-storage python library. How can i install it over jetson nano

**Comment by HemangChothani** [comment]
@Pradyumn10 Any update from your side?

**Comment by Pradyumn10** [comment]
Yeah done! 
Thank You
