### ISSUE TITLE
pip package for google cloud storage grpc

### ISSUE THREAD

**Issue by vnvo2409** [googleapis/python-storage#269]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hi,
I am working on a `GCS emulator` for `google-cloud-cpp` which supports both `Rest` ( `JSON`, `XML` ) and `gRPC` protocol for testing purposes: https://github.com/googleapis/google-cloud-cpp/issues/4751. 

I needs python code for [googleapis/google/storage/v1/storage.proto](https://github.com/googleapis/googleapis/blob/master/google/storage/v1/storage.proto) and [googleapis/google/storage/v1/storage_resources.proto](https://github.com/googleapis/googleapis/blob/master/google/storage/v1/storage_resources.proto). So far, I could run `bazel` and generate those files from [`googleapis/google/storage/v1/BUILD.bazel`](https://github.com/googleapis/googleapis/blob/fb35cd2789643e434ad36fc938f9cbe63955b6d1/google/storage/v1/BUILD.bazel#L180-L184). But it would be a lot better if there is a pip package for those file since I don't want to commit the generated files into `google-cloud-cpp`.

So I would like to ask:
- Is there any pip package for those files ?
- If there isn't, Is it ok if I wrap those generated files into a pip package just for my personal use at `google-cloud-cpp` ?

Thank you very much.

**Comment by vnvo2409** [comment]
Hi @busunkim96 

The cpp library are working on `GCS+gRPC plugin`. Since `gRPC` protocol for `GCS` is not GA, testing against production is inconvenient and expensive. So I am implementing an `GCS+gRPC` emulator in Python ( Python is simpler compared to other languages ) and I need the generated Python protos.

**Comment by tseaver** [comment]
@vnvo2409, I'm not sure why you need to have those protos published as a separate package:  couldn't you just generate them inside your emulator project?

If you *do* need to publish them to PyPI, please avoid using the "official" names for any such package you create (e.g., use a `vnvo2409-` prefix, or some such).

**Comment by vnvo2409** [comment]
Thanks to @crwilcox and #270 , I don't need to publish them to PyPI. Close this issue.
