### ISSUE TITLE
404 or 503 when patching a copied blob

### ISSUE THREAD

**Issue by jdb409** [googleapis/python-storage#276]
```
Versions:
google-api-core==1.16.0
google-auth==1.13.1
google-cloud-core==1.3.0
google-cloud-storage==1.27.0
google-resumable-media==0.5.0

Python 3.7.7
```

Over the past few weeks, we've noticed quite a few 404 and 503 status codes when patching a blob after copying it.

```
dest_blob = src_bucket.copy_blob(src_blob,
                                 dest_bucket,
                                 new_name=dest_key)
if cache_control:
    dest_blob.cache_control = cache_control
    dest_blob.patch()
```

We've been running this code in production since March and only began seeing this starting in mid August.  We have retries and it looks like it eventually works, but these are cluttering up our logs and raising false positives in our alerts.  The resulting error is either `PATCH 404 NOT FOUND` or `PATCH 503 BACKEND ERROR`.

Just to confirm, the blob that gets returned by `copy_blob` should be immediately available to perform operations upon?

We tried bumping the version of google-cloud-storage to `1.3.0`  and are still seeing this issue.

**Comment by andrewsg** [comment]
Hi @jdb409, we're now investigating this as a potential backend issue. I may be back to request more info if needed by our backend eng team. Thanks for your report!

**Comment by andrewsg** [comment]
Hi @jdb409, the backend eng team has requested additional information. Would you mind emailing the following to me at gorcester@google.com?

1) Your Cloud project name
2) The bucket affected
3) The timestamp or rough time estimate of some recent 404s you've received.

Thanks again!

**Comment by jdb409** [comment]
I spent some more time looking this over and I think it might've been a threading issue on our end.  While our code didn't change, there was an upstream change that was causing us to copy the blob twice.

What I'm thinking happened:

thread 1 - copied the blob with id 123

--context switches to thread 2--

thread 2 - copied the same blob with id 123

--context switches to thread 1--

thread 1 - tries to update the metadata of the blob, but the generation has changed.

I added a lock here and it seems to have fixed the issue. 

Does my explanation make sense to you?

**Comment by andrewsg** [comment]
I'm still a little surprised at the 404 error in particular but that does make sense.

You might benefit from using if_generation_match (or if applicable if_metageneration_match) on your requests, which will guarantee the correct behavior in concurrent situations.

**Comment by jdb409** [comment]
Ok cool, we'll look into that.  

Thanks for your help, i'm going to close the issue.
