### ISSUE TITLE
Add an API method to give us a streaming file object

### ISSUE THREAD

**Issue by dmsolow** [googleapis/python-storage#29]
It doesn't look like there's a way to get a streaming download from google storage in the Python API. We have `download_to_file` , `download_to_string`, and `download_to_filename`, but I don't see anything that returns a file-like object that can be streamed. This is a disadvantage for many file types which can usefully be processed as they download.

Can a method like this be added?

**Comment by xbrianh** [comment]
I've implemented [gs-chunked-io](https://github.com/xbrianh/gs-chunked-io) to satisfy my own needs for GS read/write streams. It's designed to compliment the Google python API.
```
import gs_chunked_io as gscio
from google.cloud.storage import Client

bucket = Client().bucket("my-bucket")
blob = bucket.get_blob("my-key)

# read
with gscio.Reader(blob) as fh:
    fh.read(size)

# read in background
with gscio.AsyncReader(blob) as fh:
    fh.read(size)

# write
with gscio.Writer("my_new_key", bucket) as fh:
    fh.write(data)
```

**Comment by petedannemann** [comment]
> @petedannemann great work - any ETA for an official release?

Release 1.10 last night included GCS functionality

**Comment by abhipn** [comment]
Any update on this?
