### ISSUE TITLE
`Blob.rewrite()` does not work with batches.

### ISSUE THREAD

**Issue by bits01** [googleapis/python-storage#32]
google-cloud-storage v1.8.0

Not sure whether rewrites are supposed to work when batched, but it would be nice and useful if they did, otherwise there's no efficient way to copy lots of blobs across buckets in different locations or with different encryption keys.

Example:
```
with gcs_client.batch():
    dest_blob.rewrite(src_blob)
```
Traceback:
```
Traceback (most recent call last):
  File "batch_test.py", line 10, in <module>
    dest_blob.rewrite(src_blob)
  File ".../pyvirtenv/python-common/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 1359, in rewrite
    rewritten = int(api_response['totalBytesRewritten'])
  File ".../pyvirtenv/python-common/lib/python2.7/site-packages/google/cloud/storage/batch.py", line 105, in __getitem__
    raise KeyError('Cannot get item %r from a future' % (key,))
KeyError: "Cannot get item 'totalBytesRewritten' from a future"
```

**Comment by tseaver** [comment]
Noted during review:  `Blob.rewrite` returns a 3-tuple, `(rewrite_token, bytes_rewritten, object_size)`, in order to permit tracking progress on the rewrite (it may only complete partially).

**Comment by billyvg** [comment]
This is also an issue when trying to use `batch()` to copy blobs while preserving the ACL of the original blob.

**Comment by cojenco** [comment]
Closing; We've added clarifications on the limited Batch support in the python client, see details in https://github.com/googleapis/python-storage/pull/1045
