### ISSUE TITLE
Avoid Authentication When Connecting to Storage Emulator

### ISSUE THREAD

**Issue by stefanadelbert** [googleapis/python-storage#324]
**Problem**
When connecting to a 3rd party storage emulator, like `gcloud-storage-emulator`, authentication is required. This requires injecting credentials into containers and adding conditional logic in code to authenticate when running against emulators.

```python
import os
from firebase_admin import initialize_app, storage

os.environ['STORAGE_EMULATOR_HOST'] = 'http://localhost:9090'
assert 'GOOGLE_APPLICATION_CREDENTIALS' not in os.environ

initialize_app()
storage.bucket() # google.auth.exceptions.DefaultCredentialsError
```

**Solution**
When `STORAGE_EMULATOR_HOST` is set, use an insecure connection, as is done for `firestore`.

**Comment by HemangChothani** [comment]
@stefanadelbert For now i think you can use a class method `create_anonymous_client` which doesn't throw an error of credential.

```python
from google.cloud import storage

client = storage.Client.create_anonymous_client()
client. project = 'project_name'
print (list(client.list_buckets()))
```

https://github.com/googleapis/python-storage/blob/6a0b8a73116472bc0d4075b0c2b364d2f81683d1/google/cloud/storage/client.py#L142-L155

**Comment by oittaa** [comment]
Is this issue abandoned?

It's quite annoying that you can't simply initiate the storage client if you ever intend to run tests.

```
client = storage.Client()
```

You always have to write some kind of wrapper like this.
```
if os.getenv("STORAGE_EMULATOR_HOST"):
    # Local testing etc.
    client = storage.Client.create_anonymous_client()
    client.project = "none"
else:
    # Normal usage
    client = storage.Client() 
```
