### ISSUE TITLE
Is there any way to select the storage class when you upload a file?

### ISSUE THREAD

**Issue by jamesmazur** [googleapis/python-storage#329]
I looked through the documentation and didn't see any way to specify the storage class using e.g. `Blob.upload_from_filename` or `Blob.upload_from_file`. The only solutions seem to be either to change the default storage class of the bucket, do the upload, and then change it back, or, alternatively, upload the file using the default storage class, and then use `update_storage_class` (which seems it will incur charges if the bucket's default storage class is anything other than Standard). This seems like a very basic feature that should be included in this library - am I missing something in the documentation? If this feature is purposely disallowed, why? It just creates extra hassle (or even charges) for anyone who wants to store files under different storage classes in the same bucket.

**Comment by HemangChothani** [comment]
@jamesmazur There are two ways to set `storage_class`, documentation of [storage class](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.storage_class)

```python
from google.cloud import storage

client = storage.Client()
bucket = client.get_bucket('your-bucket-name')
blob = bucket.blob('blob-name')

blob.storage_class = 'COLDLINE'   #storage_class_name

OR

properties = {"storageClass": 'COLDLINE'}  #storage_class_name
blob = bucket.blob('blob-name', properties=properties)

blob.upload_from_filename('file_path')

blob1 = bucket.get_blob('blob_name')
print (blob1.storage_class)   #COLDLINE

**Comment by jamesmazur** [comment]
Thanks!
