### ISSUE TITLE
Add support for the Storage Transfer service

### ISSUE THREAD

**Issue by yiga2** [googleapis/python-storage#33]
Request to support the Storage Transfer service, mainly 2 components: transferJobs and transferOperations (instantiation of jobs)

Currently only available through api: 

- https://cloud.google.com/storage/transfer/reference/rest/v1/transferJobs
- https://cloud.google.com/storage/transfer/reference/rest/v1/transferOperations 

If in the works, rough ETA would be helpful as we plan on writing corresponding Airflow operators and need to decide based on what libraries.

**Comment by tseaver** [comment]
I just checked, and there is still no generator config present in the [googleapis `storagetransfer/v1` directory](https://github.com/googleapis/googleapis/tree/master/google/storagetransfer/v1).

**Comment by frankyn** [comment]
Closing this out, we are discussing this client, but right now the only support available is through:
https://github.com/googleapis/google-api-python-client
