### ISSUE TITLE
Add Retry Strategy to manual libraries.

### ISSUE THREAD

**Issue by frankyn** [googleapis/python-storage#338]
Feature request to track work done to fix retry strategy issues in Python libraries.

Issues that have a workaround will be deduped against this bug as @crwilcox, @tritone and I organize the effort.

**Comment by andrewsg** [comment]
This is now resolved for storage. Retries are supported by default, documentation work for configuring them is pending (for now, see docstrings).

**Comment by jackkwok** [comment]
@andrewsg : What release version of `google-cloud-storage` is retries supported by default?
