### ISSUE TITLE
'Bucket.list_blobs' surface issues

### ISSUE THREAD

**Issue by tseaver** [googleapis/python-storage#35]
While investigating googleapis/google-cloud-python#4154, I noticed the following problems with `Bucket.list_blobs`:

- It exposes paging semantics, rather than a "normal" iterator.
- ~It exposes `fields`, which is probably not optimal for a method which is supposed to return populated `Blob` instances.~
- The semantics of the `versions` flag are questionable, given googleapis/google-cloud-python#2463.

Given that we are in GA, my inclination would be to add another method which addresses these issues, and docs-deprecate the existing one.  @lukesneeringer how would you like to proceed?

**Comment by cojenco** [comment]
Due to changes in the API and the client library since this issue was filed (2017), closing as obsolete. Feel free to open a fresh bug if there are issues with the current version.
