### ISSUE TITLE
Support parallel operations for copying objects

### ISSUE THREAD

**Issue by bencaine1** [googleapis/python-storage#36]
It would be great if there were a way to do the equivalent of the following command from the python API:

`gsutil -m cp -r myfolder gs://mybucket/`

You can currently upload each file individually, but this is slow for folders with many files.

I've also submitted a bug to gsutil: https://github.com/GoogleCloudPlatform/gsutil/issues/492

**Comment by wyardley** [comment]
Using  workaround similar to the above, we're getting a bunch of these errors:
`urllib3.connectionpool(WARNING): Connection pool is full, discarding connection: storage.googleapis.com`
even with fairly modest concurrency:
```python
pool = futures.ThreadPoolExecutor(max_workers=5)
```
(with default, which is 5x # of cores, we were getting even more of those errors).

Have other folks seen that? Since the calls to urllib3 are being made in the library, is there any hook to increase the connection pool size or otherwise resolve this issue?

Given that `gsutil` has an option for this, I would echo that it would be very convenient to have this implemented within the library itself.

**Comment by wyardley** [comment]
I'm also seeing some issues where the files don't exist yet if I try to access them immediately (for downloads), even after the `futures.wait()`.

**Comment by wyardley** [comment]
Hi --

code like the following was resulting in missing files sometimes:
```python
from google.cloud import storage

def get_templates(download_folder):

    # filter warnings about using default credentials
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore")
        storage_client = storage.Client()

        if os.environ.get('DEBUG', None) is None:
            # The "folder" where the files you want to download are
            bucket = storage_client.get_bucket('somebucket')
            blobs = bucket.list_blobs()

            # Static max_workers = 5 should be Ok even with 1x core
            # Also have tried default, which is like 5x num cores
            pool = futures.ThreadPoolExecutor(max_workers=5)
            downloads = []

            # Iterating through for loop one by one using API call
            for blob in blobs:
                download = pool.submit(_download_files, download_folder, bucket, blob)
                downloads.append(download)

            futures.wait(downloads)


def _download_files(download_folder, bucket, blob):
    # Have tried pre-creating these as well
    name = blob.name
    if not name.endswith("/"):
        subdir = os.path.dirname(name)

        subdir_path = '{}/{}'.format(download_folder, subdir)
        if not os.path.exists(subdir_path):
            os.makedirs(subdir_path)

        # The name includes the sub-directory path
        file_path = '{}/{}'.format(download_folder, name)
        blob.download_to_filename(file_path)
```

Even after following some suggestions from a helpful person on GCP community slack, and using `futures.as_completed()`, it still takes me about 11 seconds to copy a directory structure with 41 relatively small Jinja templates from GCS.

The same thing with, e.g., `gsutil -m cp`:
```
- [41/41 files][ 24.5 KiB/ 24.5 KiB] 100% Done                                  
Operation completed over 41 objects/24.5 KiB.                                    
gsutil -m cp -r gs://xxx /tmp  2.55s user 1.06s system 131% cpu 2.736 total
```

**Comment by benbro** [comment]
@wyardley I'm only starting to get the urllib3 warning when the thread pool size is above 10 workers.
Even then, I think it's only a warning and the same request will be retried: https://stackoverflow.com/a/53765527

**Comment by wyardley** [comment]
Yes, in the end, the urllib3 warnings were a red herring (tho pretty sure I was able to get them with fewer than 10 threads). A solutions eng on the GCP Slack gave me an example that fixes the missing files issue.

Either way, I do think this is functionality that should be builtin to the module.

**Comment by benbro** [comment]
I agree that it should be part of the library.
What fixed the missing files issue?

**Comment by wyardley** [comment]
It seemed to have to do with using `futures.wait()`. I adapted a variation that @domZippilli kindly threw together and that’s worked relatively well, though it’s not quite as simple as the examples above. Maybe he’d be willing to gist it here.

**Comment by domZippilli** [comment]
Of course! [Here's the gist](https://gist.github.com/domZippilli/70a56e29ed329225380d518307cfbe73). Usual disclaimer that this is offered as-is, no guarantees that it will work or even not hurt you, use at your own risk.

**Comment by wyardley** [comment]
I had also tried some simpler suggestions for fixing the above (including, if memory serves, returning something from `_download_files()`, and they didn't seem to work either.

**Comment by benbro** [comment]
I think that the following also guarantees that all task complete.
```python
with ThreadPoolExecutor(max_workers=5) as executor:
  results = executor.map(upload, files)
for res in results:
  pass
```

**Comment by domZippilli** [comment]
It should! Executor's `map` function rules. And I believe the iterator yields the _result_ of each future, so that is a succinct way of doing the same.

**Comment by hector-sab** [comment]
Another workaround would be to use [sh](https://pypi.org/project/sh/) and do something like
```python
import sh
sh.gsutil("-m cp data gs://mybucket/data".split())
```

**Comment by 1fish2** [comment]
@hector-sab Shelling out to `gsutil` has significant limitations:

* Uploads don't create the empty "placeholder" directory-like entries that are needed to make `gcsfuse` run at a reasonable speed. It's a 10x speed factor.
* Parallel downloads will put all the files into the same directory except when using `-r` to recursive download a directory. So I can't give it a list of files from multiple directories to put into multiple directories.
* Error handling and recovery: Can one reliably parse its stdout to tell which transfers succeeded?
