### ISSUE TITLE
No labels returned from `bucket.labels`

### ISSUE THREAD

**Issue by Jaxing** [googleapis/python-storage#386]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-storage/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Ubuntu 20.04
  - Python version: Python 3.7.9
  - pip version: pip 20.3.3
  - `google-cloud-storage` version: Name: google-cloud-storage Version: 1.35.0

#### Steps to reproduce

  1. Create a bucket using terraform, this is the code for my bucket
 ```resource google_storage_bucket NAME {
  name     = "NAME"
  location = local.region

  versioning {
    enabled = true
  }
  labels = {
    project = "project"
    environment = "test"
  }
}```
  2. 
``` from google.cloud.storage import Client, Blob, Bucket
     c = Client()
     b = c.bucket('name')
     b.labels
```
output
```
{}
```
  3. run `gsutil label get gs://name
  output 
```
{
  "environment": "test",
  "project": "project"
}
``` 
So the issue is that the labels that I get from `bucket.labels` are different (they don't exists) from the labels I get from gsutils and that I see in the UI.

**Comment by andrewsg** [comment]
Hello. As per the docstring for the function Client.bucket() only creates an in-memory object, it does not make an API call to fetch metadata. For your use case, use Client.get_bucket(), which both creates the object in-memory and also issues an API call. Alternatively you can use Client.bucket() but then call b.reload() to make the API call after the fact.

I think this will probably resolve the issue, but if it persists even when following these instructions, please don't hesitate to comment here again. Thanks!

**Comment by Jaxing** [comment]
Thanks for the response @andrewsg, this works!
