### ISSUE TITLE
Is it possible to use the predefined_acl keyword argument to upload a publicly readable blob in one step?

### ISSUE THREAD

**Issue by gaborfeher** [googleapis/python-storage#389]
#### Environment details

  - OS type and version: Ubuntu 18.04
  - Python version: `Python 3.6.9`
  - pip version: `pip 9.0.1 (python 3.6)`
  - `google-cloud-storage` version: `1.36.1`

#### Steps to reproduce

  1. Run the below code sample
  2. Check the created files on google cloud console

#### Code example

```
from google.cloud import storage
import time
                                                                                                      
MY_BUCKET = '...'
        
client = storage.Client()
bucket = client.get_bucket(MY_BUCKET)                                                                 
        
blob = bucket.blob('test/t1.txt')
blob.upload_from_string('hello, world')
time.sleep(1)
blob.make_public()

blob = bucket.blob('test/t2.txt')
blob.upload_from_string('hello, world', predefined_acl='publicRead')

blob = bucket.blob('test/t3.txt')
blob.upload_from_string('hello, world')
```

#### Screenshot from Google Cloud Console

![console_screenshot](https://user-images.githubusercontent.com/11962088/110204898-c8cbb980-7e75-11eb-82a1-e9bc79ba0ff9.png)

#### Expected behavior

I would expect `t2.txt` to look the same as `t1.txt`, i.e. to be "Public to Internet".

I don't really understand the difference between `t2.txt` and `t3.txt` but it feels like that adding `publicRead` to `t2.txt` takes away the permissions of the bucket owner from the file. So, not sure, but what I might truly need is the ability to set the union of `publicRead` and `bucketOwnerFullControl` on the file.

I can imagine that I am using this API incorrectly but then maybe the docs should be improved. And my ultimate question is, whether there is a way to upload a public file to GCS in one step.

**Comment by frankyn** [comment]
Hi @gaborfeher,

I was able to create a public object using `predefined_acl` in the same upload request. 
Could you run the following example and see if you get: `<ACL Entity: allUsers (READER)>`?

```
from google.cloud import storage

client = storage.Client()

bucket = client.bucket("bucket-name")
blob = bucket.blob("new_blob_with_predefined")

blob.upload_from_string("hello", predefined_acl='publicRead')

print(blob.acl.get_entities())
```

Enabling logging can help suss out what may be occurring as well (Python 3 example):

```
from google.cloud import storage
import http
http.client.HTTPConnection.debuglevel=5

client = storage.Client()

bucket = client.bucket("anima-frank")
blob = bucket.blob("new_blob_with_predefined")

blob.upload_from_string("hello", predefined_acl='publicRead')

print(blob.acl.get_entities())
```

**Comment by frankyn** [comment]
Hi @gaborfeher,

Closing issue out, as I'm guessing the question was addressed. If not, please feel free to reopen!
