### ISSUE TITLE
Add encryption_key param to Blob.from_string

### ISSUE THREAD

**Issue by harrydrippin** [googleapis/python-storage#390]
**Is your feature request related to a problem? Please describe.**
When I need to generate `Blob` object by using factory function `Blob.from_string`, I cannot use customer-supplied encryption option smoothly. I always need to assign internal variables like below:

```python
blob = Blob.from_string("gs://somewhere/sample.txt", client=client)
blob._encryption_key = encryption_key
```

 **Describe the solution you'd like**
* Add `encryption_key` parameter to `Blob.from_string`.

 **Describe alternatives you've considered**
Maybe adding explicit setter for `_encryption_key` is possible, but I think the solution above is more effective for resolving this issue.

 **Additional context**
I have a draft PR for this fix, so please review it if this request is acceptable. Thanks!

**Comment by cojenco** [comment]
Thank you for filing the issue and submitting a PR. Your proposal looks great. After looking into the alternatives, I think it makes sense to directly add encryption_key param to Blob.from_string. Would you mind adding unit tests to the PR? For example, if you could add ‘test_from_string_w_encryption_key’ in [this test file](https://github.com/googleapis/python-storage/blob/d52853b420f50012e02c395f5407e3018922c048/tests/unit/test_blob.py#L4663 ). Thanks!

**Comment by harrydrippin** [comment]
@cojenco Thank you for your support. I added [the test on my branch](https://github.com/googleapis/python-storage/blob/327183d186223589bebd4b28de45db4d35b0a617/tests/unit/test_blob.py#L4676) as you mentioned and marked my PR as ready for review.

**Comment by cojenco** [comment]
Thanks again @harrydrippin for your contribution. Considering future changes and consistency, our team has decided to go a different direction with getters and setters. [This PR](https://github.com/googleapis/python-storage/pull/409) is currently under review. Hope this resolves your issue, thanks!
