### ISSUE TITLE
Support for GOOGLE_CLOUD_KEYFILE_JSON as in ruby client library

### ISSUE THREAD

**Issue by phoet** [googleapis/python-storage#395]
The ruby clients support passing the client configuration as an environment variable (`GOOGLE_CLOUD_KEYFILE_JSON`) cointaining a json blob instead of a path to a json config file.

https://github.com/googleapis/google-cloud-ruby/blob/1a7cfef70298276a9203658748e9d70edfcfb2d5/google-cloud-datastore/samples/README.md#authenticating

It would be super helpful (and less confusing) if there was a similar option in the python library.

**Comment by tseaver** [comment]
Related: https://github.com/googleapis/python-cloud-core/pull/54/ adds a `from_service_account_info` factory to the client base class, which would allow for the following:

```python
import os
from google.cloud.storage import Client

keyfile_json = os.getenv("GOOGLE_CLOUD_KEYFILE_JSON")
if keyfile_json is not None:
    client = Client.from_service_account_info(keyfile_json)
else:  # fall back to normal env vars
    client = Client()
```

**Comment by tseaver** [comment]
Closing, given that the `api-core` PR has landed, and the spelling above accomplishes the requested usage.
