### ISSUE TITLE
Add Python ConnectionError in list of retry

### ISSUE THREAD

**Issue by nitishxp** [googleapis/python-storage#426]
Hi, Could you add 
https://docs.python.org/3/library/exceptions.html#ConnectionError just like https://github.com/googleapis/python-bigquery/blob/be3c49a72f0e04de4055f5ca7a99f821c2c8f240/google/cloud/bigquery/retry.py#L26 in list of retry

This ConnectionError is seperate from requests.ConnectionError

**Comment by cojenco** [comment]
Hi @nitishxp, we are looking into this. Thanks for filing this as a separate issue per the [previous discussion](https://github.com/googleapis/python-storage/issues/414#issuecomment-832065858).

**Comment by cojenco** [comment]
Hi @nitishxp, to help us better understand the failure cases, could you let us know more about under what circumstances have you encountered this ConnectionError? Thanks!

**Comment by nitishxp** [comment]
@cojenco Mostly in Cloud function when there are subsequent reinvocation of Cloud Function this error is generated is faced in Big Query as well as storage.
