### ISSUE TITLE
Change `blob.compose` to fit API behavior

### ISSUE THREAD

**Issue by cojenco** [googleapis/python-storage#453]
Currently `blob.compose()` is misusing `if_generation_match` as a list of [`sourceObjects[].objectPreconditions.ifGenerationMatch`](https://cloud.google.com/storage/docs/json_api/v1/objects/compose#request-body) sent with the API request body. Based on the [doc](https://cloud.google.com/storage/docs/json_api/v1/objects/compose#parameters), `if_generation_match` is an optional query parameter that makes the operation conditional only when the composed object's current generation matches the given value.

**Comment by tritone** [comment]
Just to clarify-- you mean that you think `if_generation_match` should be applied to the destination object and not the source objects, correct? This is a behavior change so it definitely requires some scrutiny (unless there's no way it could've worked as it is currently).

**Comment by cojenco** [comment]
@tritone Right! According to the API doc, `if_generation_match` should be applied to the **destination object**, and serves as the preconditions for retries.
