### ISSUE TITLE
Support context manager, so each developer can use this module more efficiently

### ISSUE THREAD

**Issue by nnaka2992** [googleapis/python-storage#471]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Currently, the Client class does not support context manager.  Supporting context manager would make programmers easy to write and maintenance their code.

 **Describe the solution you'd like**
Add `__enter__` method which returns self and `__exit__`  method to free instance  in order to enable contextmanager. Works as following would be perfect.
```
with storage.Client() as client:
    bucket = client.get_bucket(bucket_name)
    blob = bucket.blob(file_name
```

**Comment by tseaver** [comment]
As of https://github.com/googleapis/python-cloud-core/pull/100/ (merged released with `google-cloud-core 1.7.0`), the following works:

```
import contextlib
from google.cloud.storage import Client

client = Client()

with contextlib.closing(client):
    do_something_with(client)
```

AFAICT, that addresses this feature request.

**Comment by danielduhh** [comment]
Should we bump our core dependency to 1.7.0? @tseaver

**Comment by tseaver** [comment]
@danielduhh 
> Should we bump our core dependency to 1.7.0?

I don't think so -- `google-cloud-storage` works fine without that version, it is just missing this feature.

**Comment by danielduhh** [comment]
@nnaka2992 could you verify that pinning [google-cloud-storage](https://github.com/googleapis/python-storage/blob/master/setup.py#L32) to >=1.7.0 resolves this issue?
