### ISSUE TITLE
Can not detect if bucket is requester-pays without using a user project

### ISSUE THREAD

**Issue by hurrialice** [googleapis/python-storage#479]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS type and version: `Ubuntu 20.04`
  - Python version: `3.8.5`
  - pip version: `20.0.2`
  - `google-cloud-storage` version: `1.39.0`

#### Code example

I was trying to see if a bucket is requester-pay or not. Following the instructions [here](https://cloud.google.com/storage/docs/using-requester-pays#storage-get-requester-pays-status-python), which is essentially

```
bucket = storage_client.get_bucket(bucket_name)
requester_pays_status = bucket.requester_pays
``` 

with my bucket of interest, I get:
```
>>> from google.cloud import storage
>>> bucket_name = "fc-5d8d0763-22af-45d3-ad83-5a28c7ba4d8d"
>>> c = storage.Client()
>>> b = c.get_bucket(bucket_name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/client.py", line 760, in get_bucket
    bucket.reload(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/bucket.py", line 950, in reload
    super(Bucket, self).reload(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/_helpers.py", line 208, in reload
    api_response = client._get_resource(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/client.py", line 368, in _get_resource
    return self._connection.api_request(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/_http.py", line 78, in api_request
    return call()
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/retry.py", line 285, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/retry.py", line 188, in retry_target
    return target()
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 GET https://storage.googleapis.com/storage/v1/b/fc-5d8d0763-22af-45d3-ad83-5a28c7ba4d8d?projection=noAcl&prettyPrint=false: Bucket is requester pays bucket but no user project provided.
```

It seems I have to use `bucket` instead of `get_bucket()` for the code to work, but it says the bucket is not requester-pay.

```
>>> b = c.bucket(bucket_name)
>>> b.requester_pays
False
```
which does not align with the result from `gsutil`:

```
$ gsutil requesterpays get gs://fc-5d8d0763-22af-45d3-ad83-5a28c7ba4d8d
BadRequestException: 400 Bucket is requester pays bucket but no user project provided.
```

Thanks!

**Comment by ddelgrosso1** [comment]
Hi @hurrialice,

In looking at the information you provided it would appear that the behavior of ```get_bucket``` and ```gsutil``` are throwing the correct exception per the [documentation](https://cloud.google.com/storage/docs/requester-pays#requirements) for when the requester does not have a billing project provided. Can you verify that the requester does have a billing project?

Additionally, in the example you provided where you are using ```bucket(bucket_name)``` this is actually a factory constructor that is being called and not a means of retrieving a bucket. The relevant documentation is [here](https://googleapis.dev/python/storage/latest/client.html#google.cloud.storage.client.Client.bucket).

**Comment by hurrialice** [comment]
>  behavior of get_bucket and gsutil are throwing the correct exception per the documentation for when the requester does not have a billing project provided

The documentation says:

```
  bucket = storage_client.get_bucket(bucket_name)
  requester_pays_status = bucket.requester_pays

  if requester_pays_status:
      print("Requester Pays is enabled for {}".format(bucket_name))
  else:
      print("Requester Pays is disabled for {}".format(bucket_name))
```

which indicates that I could get the requester-pay status of a bucket from the metadata regardless of whether I input a user project, which is definitely not what I see:

```
>>> from google.cloud import storage
>>> bucket_name = "fc-5d8d0763-22af-45d3-ad83-5a28c7ba4d8d"
>>> c = storage.Client()
>>> b = c.get_bucket(bucket_name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/client.py", line 760, in get_bucket
    bucket.reload(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/bucket.py", line 950, in reload
    super(Bucket, self).reload(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/_helpers.py", line 208, in reload
    api_response = client._get_resource(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/client.py", line 368, in _get_resource
    return self._connection.api_request(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/_http.py", line 78, in api_request
    return call()
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/retry.py", line 285, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/retry.py", line 188, in retry_target
    return target()
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
```

 In other words, the above code in the document won't run at all if `requester_pays_status = False`. Is there something wrong with the documentation?

> in the example you provided where you are using bucket(bucket_name) this is actually a factory constructor that is being called and not a means of retrieving a bucket

This is good to know.

So, my question is, **how to use python storage API to find out (preferably gets True / False) if a bucket is requester-pay?** I have tried 
```
bucket = storage_client.get_bucket(bucket_name, user_project = "broad-getzlab-wolf-wgs-hg38")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_bucket() got an unexpected keyword argument 'user_project'
```
but it's not working either.

> Can you verify that the requester does have a billing project?

Yes I do have one (see above), but I don't know where to put this argument to get the code working.

**Comment by ddelgrosso1** [comment]
> > Can you verify that the requester does have a billing project?
> 
> Yes I do have one (see above), but I don't know where to put this argument to get the code working.

The project argument can be passed to the storage client constructor as documented [here](https://googleapis.dev/python/storage/latest/client.html#module-google.cloud.storage.client) or you can set an [environment](https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable) variable with the path to a key file.

I did some testing locally to verify that the sample does behave as documented when passed a project. If after setting the project you still encounter issues, please let me know.

**Comment by ddelgrosso1** [comment]
Hi @hurrialice,

I just wanted to check if the above documentation helped you set a project and if so, did it resolve your issue?

**Comment by hurrialice** [comment]
Hi @ddelgrosso1 

Thanks for your explanation! I'd like to confirm with you if this is intended behaviour --

I initiated the `Client` with `project` argument:
```
from google.cloud import storage
bucket_name = "fc-5d8d0763-22af-45d3-ad83-5a28c7ba4d8d"
c = storage.Client(project = "broad-getzlab-wolf-wgs-hg38")
b = c.get_bucket(bucket_name)
```
and I got this error again:

```
---------------------------------------------------------------------------
BadRequest                                Traceback (most recent call last)
<ipython-input-56-7ac1b100cdc7> in <module>
----> 1 b = c.get_bucket(bucket_name)

/usr/local/lib/python3.8/dist-packages/google/cloud/storage/client.py in get_bucket(self, bucket_or_name, timeout, if_metageneration_match, if_metageneration_not_match, retry)
    758         """
    759         bucket = self._bucket_arg_to_bucket(bucket_or_name)
--> 760         bucket.reload(
    761             client=self,
    762             timeout=timeout,

/usr/local/lib/python3.8/dist-packages/google/cloud/storage/bucket.py in reload(self, client, projection, timeout, if_metageneration_match, if_metageneration_not_match, retry)
    948             (Optional) How to retry the RPC. See: :ref:`configuring_retries`
    949         """
--> 950         super(Bucket, self).reload(
    951             client=client,
    952             projection=projection,

/usr/local/lib/python3.8/dist-packages/google/cloud/storage/_helpers.py in reload(self, client, projection, if_generation_match, if_generation_not_match, if_metageneration_match, if_metageneration_not_match, timeout, retry)
    206             if_metageneration_not_match=if_metageneration_not_match,
    207         )
--> 208         api_response = client._get_resource(
    209             self.path,
    210             query_params=query_params,

/usr/local/lib/python3.8/dist-packages/google/cloud/storage/client.py in _get_resource(self, path, query_params, headers, timeout, retry, _target_object)
    366                 If the bucket is not found.
    367         """
--> 368         return self._connection.api_request(
    369             method="GET",
    370             path=path,

/usr/local/lib/python3.8/dist-packages/google/cloud/storage/_http.py in api_request(self, *args, **kwargs)
     76             if retry:
     77                 call = retry(call)
---> 78         return call()

/usr/local/lib/python3.8/dist-packages/google/api_core/retry.py in retry_wrapped_func(*args, **kwargs)
    283                 self._initial, self._maximum, multiplier=self._multiplier
    284             )
--> 285             return retry_target(
    286                 target,
    287                 self._predicate,

/usr/local/lib/python3.8/dist-packages/google/api_core/retry.py in retry_target(target, predicate, sleep_generator, deadline, on_error)
    186     for sleep in sleep_generator:
    187         try:
--> 188             return target()
    189 
    190         # pylint: disable=broad-except

/usr/local/lib/python3.8/dist-packages/google/cloud/_http.py in api_request(self, method, path, query_params, data, content_type, headers, api_base_url, api_version, expect_json, _target_object, timeout)
    482 
    483         if not 200 <= response.status_code < 300:
--> 484             raise exceptions.from_http_response(response)
    485 
    486         if expect_json and response.content:

BadRequest: 400 GET https://storage.googleapis.com/storage/v1/b/fc-5d8d0763-22af-45d3-ad83-5a28c7ba4d8d?projection=noAcl&prettyPrint=false: Bucket is requester pays bucket but no user project provided.
```

Is this intended or did I miss something? I thought I have provided the user project when I called `Client`?

**Comment by ddelgrosso1** [comment]
Hi @hurrialice 

After speaking with some teammates I have some further clarification. Can you try either of the 2 examples below and see if they successfully return the requester pays status for you?

`bucket_obj = client.bucket(bucket_name, user_project=user_project)
 bucket_obj.reload()`
 
 or
 
 `bucket_obj = client.bucket(bucket_name, user_project=user_project)
  bucket = client.get_bucket(bucket_obj)`

**Comment by hurrialice** [comment]
Hi @ddelgrosso1 
Both worked for me. Thanks so much for your clarification. I will close this issue now!
