### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by AntonLazarchik** [googleapis/python-storage#501]
google-cloud-storage-1.41.0
https://github.com/googleapis/python-storage/blob/6486010c5835d25a9284c6b17730a3c31177e55a/google/cloud/storage/blob.py#L1520

Traceback (most recent call last):
  File "", line 40, in <module>
    GoogleStorage().download_blob_as_string(uri='')
  File "", line 23, in download_blob_as_string
    return blob.download_as_string(retry=custom_retry)
  File "\venv\lib\site-packages\google\cloud\storage\blob.py", line 1520, in download_as_string
    warnings.warn(
TypeError: expected string or bytes-like object

print(type(_DOWNLOAD_AS_STRING_DEPRECATED))
warnings.warn(
    _DOWNLOAD_AS_STRING_DEPRECATED, PendingDeprecationWarning, stacklevel=2
)
![image](https://user-images.githubusercontent.com/60065928/125602238-78817e07-5675-4929-9fc8-b6c7c071a9c3.png)

**Comment by nicwest** [comment]
https://github.com/googleapis/python-storage/blob/6486010c5835d25a9284c6b17730a3c31177e55a/google/cloud/storage/blob.py#L138-L141 
dangling comma at the end of the line

**Comment by nicwest** [comment]
same thing with `_COMPOSE_IF_METAGENERATION_LIST_DEPRECATED`

https://github.com/googleapis/python-storage/blob/6486010c5835d25a9284c6b17730a3c31177e55a/google/cloud/storage/blob.py#L129-L134
