### ISSUE TITLE
Remove deprecated function download_as_string() in Example Usage

### ISSUE THREAD

**Issue by richardevs** [googleapis/python-storage#504]
download_as_string() is deprecated but still being shown on the Example Usage in README.rst.

Suggest to remove deprecated function download_as_string(), replace with download_as_bytes(). [1]

README.rst
```diff
- 101    print(blob.download_as_string())
+ 101    print(blob.download_as_bytes())
```

[1] https://github.com/googleapis/python-storage/blob/master/google/cloud/storage/blob.py#L138

**Comment by parthea** [comment]
Hi @richardevs,

PRs are welcome!
