### ISSUE TITLE
blob.download_as_string() raises TypeError: expected string or bytes-like object in version 1.41.0

### ISSUE THREAD

**Issue by TheBirdsNest** [googleapis/python-storage#510]
Version `google-cloud-storage==1.41.0`

When calling `blob.download_as_string()` we get a TypeError.

Working in version `1.40.0`

Error Output:
```
unencrypted_secret = self.decrypt(blob.download_as_string())
File "/usr/local/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 1520, in download_as_string
warnings.warn(
TypeError: expected string or bytes-like object
```

**Comment by Breathtender** [comment]
Hi @TheBirdsNest, thanks for this report!

This was actually just reported and addressed in #501 and #504

Long story short; `download_as_string()` is deprecated, but our deprecation message had a lingering comma that caused it to be the wrong type, so it doesn't tell you that it's deprecated, it just fails. You should be able to fix this by replacing `download_as_string()` with `download_as_bytes()`

If you could give that a try and let us know if that works or if you run into any issues, that would be great, thanks!

**Comment by Sabreware** [comment]
changing to download_as_bytes works.

**Comment by TheBirdsNest** [comment]
Thanks @Breathtender; that worked perfectly. 
Apologies for not doing a thorough enough search for already open issues!

I appreciate the quick response :D
