### ISSUE TITLE
Retry did not happened

### ISSUE THREAD

**Issue by nitishxp** [googleapis/python-storage#527]
Hi,

Lib version : google-cloud-storage==1.38.0

While patching a bucket I got this error 
`
in create_buckets bucket_obj.patch() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/bucket.py", line 1067, in patch super(Bucket, self).patch( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/_helpers.py", line 335, in patch api_response = client._connection.api_request( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/_http.py", line 78, in api_request return call() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/_http.py", line 484, in api_request raise exceptions.from_http_response(response) google.api_core.exceptions.ServiceUnavailable: 503 PATCH https://storage.googleapis.com/storage/v1/b/bucket?projection=full&prettyPrint=false: We encountered an internal error. Please try again.`

**Comment by BrennaEpp** [comment]
Hi @nitishxp, thanks for the question. Are you using preconditions when patching the bucket? 

Bucket patch operations are [conditionally idempotent](https://cloud.google.com/storage/docs/retry-strategy#conditional_idempotency), that is, they are only safe to retry with a precondition. Update/patch requests for buckets should have IfMetagenerationMatch as HTTP precondition. [See here](https://github.com/googleapis/python-storage/blob/master/docs/generation_metageneration.rst#using-if_metageneration_match) on how to use the IfMetagenerationMatch precondition in python.

**Comment by nitishxp** [comment]
So i need to use

```
from google.cloud.storage.retry import DEFAULT_RETRY
bucket.patch(retry=DEFAULT_RETRY) 

```

**Comment by BrennaEpp** [comment]
You probably would not want to use the default retry behaviour for a patch (as in your first example), as it might retry the patch even if it was completed but the server returned an error ([see an example of why that may happen here](https://cloud.google.com/storage/docs/generations-preconditions#retry-scenario)). Repeating a patch can leave the bucket in a different state than performing that same patch just once. 

Instead, you may want to only retry if you know the patch was not applied the first time, which you can tell by checking that the Metageneration has not changed. Take these steps  to do so: 

1. Get the metadata for your bucket to determine its current generation
2. Send the patch request with an `if_metageneration_match` precondition that uses that generation number

You do not have to explicitly set the retry policy as the default is to only retry a `patch()` if `if_metageneration_match` is specified as a parameter. For example, these two code samples will have the same results:
```python
from google.cloud.storage.retry import DEFAULT_RETRY_IF_METAGENERATION_SPECIFIED
...
currMetageneration = bucket.metageneration
bucket.patch(if_metageneration_match=currMetageneration, retry=DEFAULT_RETRY_IF_METAGENERATION_SPECIFIED) 
```
```python
currMetageneration = bucket.metageneration
bucket.patch(if_metageneration_match=currMetageneration)
```

**Comment by nitishxp** [comment]
Thanks @BrennaEpp

**Comment by BrennaEpp** [comment]
You're welcome @nitishxp 
Closing the issue. Feel free to reopen if you have any more questions about this.
