### ISSUE TITLE
Redesign of API so it does not need storage.buckets.get access for every single operation.

### ISSUE THREAD

**Issue by seperman** [googleapis/python-storage#528]
**Is your feature request related to a problem? Please describe.**
Based on the doc examples and a quick browsing through the code of this library, it requires `storage.buckets.get` on almost every single operation on blobs. 

Current read operation:

```
    bucket = storage_client.bucket(bucket_name)  # needs `storage.buckets.get`
    blob = bucket.blob(source_blob_name)
    blob.download_to_filename(destination_file_name)
```

Current delete operation:

```
    bucket = storage_client.bucket(bucket_name)  # needs `storage.buckets.get`
    blob = bucket.blob(blob_name)
    blob.delete()
```

 **Describe the solution you'd like**
Looking at the Rest API, there is no need to have the `storage.buckets.get` to do basic CRUD operations on the blobs. The `storage.buckets.get` permission is way too permissive and shouldn't be required for CRUD operations on blobs.

 **Describe alternatives you've considered**
The alternative I'm considering is hitting the Rest API directly and not using this library.

**Comment by seperman** [comment]
never mind.

**Comment by subodh101** [comment]
In case someone comes across a similar problem:

bucket = client.bucket("")  # <---- use "bucket" instead of "get_bucket"
