### ISSUE TITLE
503 when using bucket.rename_blob()

### ISSUE THREAD

**Issue by SumithRZT** [googleapis/python-storage#532]
```
google.api_core.exceptions.ServiceUnavailable: 503 POST https://storage.googleapis.com/storage/v1/b/doc_corpus/o/receipts%2Freceipts%2F1087-receipt.jpg/copyTo/b/doc_corpus/o/receipts%2F1087-receipt%2F1087-receipt.jpg?prettyPrint=false: We encountered an internal error. Please try again
```

Getting the above error while running the following python code

```py
import google.cloud.storage as store
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/sumithkrishna/Downloads/key.json')

client = store.Client(credentials=credentials)
bucket = client.get_bucket("doc_corpus")

blobs = bucket.list_blobs()
files = []
i = 0
for blob in blobs:
    if blob.name.startswith("receipts/receipts") and blob.name.endswith(".jpg"):
        print(blob.name+" - "+blob.name.split("/")[2]+ " - "+ 'receipts/'+blob.name.split("/")[2][:-4]+" -- "+str(i))
        files.append(blob.name.split("/")[2][:-4])
        bucket.rename_blob(blob, 'receipts/'+blob.name.split("/")[2][:-4]+'/'+blob.name.split("/")[2])
        i+=1
```

It ran fine for 81 images and got this error afterwards

**Comment by BenWhitehead** [comment]
Hi @SumithRZT, since v1.34.0 the library should automatically retry the request for you if you specify the [`if_generation_match` parameter](https://googleapis.dev/python/storage/1.34.0/buckets.html#google.cloud.storage.bucket.Bucket.rename_blob) correlated with the destination object. If you're creating a new object, then a generation value of `0` can should be specified.

**Comment by tritone** [comment]
Also note that you can retry without if_generation_match if you specify `retry=DEFAULT_RETRY` in your call to rename_blob (though this comes with risks from an idempotency perspective).
