### ISSUE TITLE
Conflict with libraries google-cloud-storage and google-auth 

### ISSUE THREAD

**Issue by mariemzyr** [googleapis/python-storage#535]
Hello. I will need your help ! :) 

I code in python a flask api to generate a Google Signed Url.
However for that I need 2 libraries, so I wrote a requirements file that I will run in a docker file.

I put in the post the three files (requirements.txt, Dockerfile and app.py).

I don't understand why when I specify the two versions (which when I try on a cloud function, it works. I use python 3.7 with google-cloud-storage==1.38.0 and google-auth==1.30.2), I also try with the two latest versions, I get this error : 
<img width="1151" alt="Capture d’écran 2021-08-06 à 17 29 39" src="https://user-images.githubusercontent.com/73951201/128534722-228269f9-d410-4912-a91c-936f603a7aba.png">

<img width="471" alt="Capture d’écran 2021-08-06 à 17 28 15" src="https://user-images.githubusercontent.com/73951201/128534511-540f9a66-ab8b-4c9d-9f36-1d44fa1a4dad.png">
<img width="457" alt="Capture d’écran 2021-08-06 à 17 28 37" src="https://user-images.githubusercontent.com/73951201/128534561-fbbecf1f-7f9b-493f-8a22-e207eed0ae75.png">
<img width="759" alt="Capture d’écran 2021-08-06 à 17 29 05" src="https://user-images.githubusercontent.com/73951201/128534631-c02a74a6-5b9b-48ce-b4c6-9bd28844c35f.png">

**Comment by BenWhitehead** [comment]
Hi @mariemzyr the dependency `google-crc32c` is actually dependent upon a native library which isn't built for alpine-linux, so pip is ultimately unable to resolve the dependency and you receive the error you provided. The easiest way to get unblock is to switch the base image you're using:

```diff
- FROM python:3.7-alpine
+ FROM python:3.7
```

Switching to the non-alpine version will allow the resolution of the wheel which is built for libc.

If you're not able to switch the base image, you'll probably need to try building `google-crc32c` yourself. We have some instructions included in the repo if you need to go this route https://github.com/googleapis/python-crc32c/blob/master/BUILDING.md.

**Comment by mariemzyr** [comment]
Thank you very much for your help, the problem was indeed the alpine version of python. 
Good continuation :)
