### ISSUE TITLE
Ensure blob.download_to_filename() is atomic

### ISSUE THREAD

**Issue by enaskopelja** [googleapis/python-storage#556]
#### Environment details

  - OS type and version: `macOS Big Sur 11.4`
  - Python version: `3.9.6`
  - pip version: `21.1.2`
  - `google-cloud-storage` version: `1.42.0`

### Problem you have encountered:
If `blob.download_to_filename()` is interrupted by KeyboardInterrupt the result is an empty file.

### What you expected to happen:
The function should detect download hasn't finished and delete the created file (should be atomic).

### Steps to reproduce:
1. Ensure the bucket you’re downloading from has enough blobs to allow for the programme to keep running for steps 2 and 3 (10 should be enough)
2. run the following python script:

``` python
from pathlib import Path
from google.cloud.storage import Client

if __name__ == '__main__':
    client = Client()
    for blob in client.list_blobs(_bucket_name_):
        destination_path = Path(blob.name)
        destination_path.parent.mkdir(parents=True, exist_ok=True)
        blob.download_to_filename(str(destination_path))
```

3. Send a `KeyboardInterrupt` signal
4. Look for a file containing 0B of data

**Comment by andrewsg** [comment]
Hmm, under what circumstances will this behavior cause an issue? Is it really safe to execute a filesystem operation like delete after receiving a keyboard interrupt? Is this problem observed with non-user-instigated exceptions?

**Comment by andrewsg** [comment]
Closing this for now; I'm open to reopening this with a more clear use case or comparison to the behavior of other similar libraries.
