### ISSUE TITLE
Update shared conformance tests

### ISSUE THREAD

**Issue by tseaver** [googleapis/python-storage#57]
~~We need to add a test suite which exercises the cross-language tests and fix anything where we don't pass.~~

We need to *update* the shared conformance tests to match the current spec:

- [Proto spec for the testcase file](https://github.com/googleapis/conformance-tests/blob/master/storage/v1/proto/google/cloud/conformance/storage/v1/tests.proto)
- [Testcase file](https://github.com/googleapis/conformance-tests/blob/master/storage/v1/v4_signatures.json)

/cc @frankyn

**Comment by frankyn** [comment]
@tseaver I misunderstood this file -> https://github.com/googleapis/python-storage/blob/master/tests/unit/url_signer_v4_test_data.json

I understood this JSON file as being the cross-language conformance tests.

**Comment by tseaver** [comment]
Hmmm, looks like that *is* conformance tests.  Dunno how I missed that they existed already.

**Comment by frankyn** [comment]
+1, I recently changed the schema and added conformance tests for Signed Policies.

**Comment by tseaver** [comment]
Suggested implemenation plan:

- [ ] Move the test drivers for signing out into a separate file, like the `test_cross_language.py` file in `python-firestore`.
- [ ] Rename the data file to match the upstream name (`v4_signatures.json`).
- [ ] Update the test drivers to match the new schema, if needed, and fix anything broken.
- [ ] Add a test driver for the Signed Policy testcases.

**Comment by tseaver** [comment]
I have a branch which implements the first two steps cleanly, and a stash for the third one, where some of the tests no longer pass.  Actually landing the new tests is going to need to wait for PRs #48 and #56 to land, I think.

**Comment by frankyn** [comment]
@HemangChothani, @tseaver is tracking conformance test updates in here. Referenced issues are merged/unblocked.

**Comment by frankyn** [comment]
This was fixed by @IlyaFaer
