### ISSUE TITLE
Adding function index in document

### ISSUE THREAD

**Issue by yingbo** [googleapis/python-storage#610]
In the python API document of a class, there should be an index of all functions of the class. For example, in this page: https://googleapis.dev/python/storage/1.42.3/client.html, it is very hard to tell which functions are available in "class google.cloud.storage.client.Client". A functions/members index on the right side of page will be very helpful.

**Comment by tseaver** [comment]
@yingbo Thanks for the suggestion!  Our docs pages are generated from [Sphinx](https://www.sphinx-doc.org/en/master/) -- is there a particular Sphinx feature which corresponds to the index you are suggesting?

**Comment by cojenco** [comment]
Hi @yingbo, the docs are in the process of being updated to cloud.google.com. Please checkout the [updated doc for class `Client` ](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.client.Client), and let us know if you have any feedback. Thanks!

**Comment by yingbo** [comment]
It's amazing! Thanks for the clear documents.
