### ISSUE TITLE
Add a py.typed file for submodule

### ISSUE THREAD

**Issue by crwilcox** [googleapis/python-storage#621]
To be in accordance with [PEP 561](https://www.python.org/dev/peps/pep-0561/) we should add a py.typed file to google/cloud/storage/py.typed

The file can be empty but does need to be present for some type checkers.

**Comment by crwilcox** [comment]
Do note, you may need to run mypy, pyright, pytype against our samples before merging. It will ensure that we aren't exposing users to failing type checks.

Ideally we would add this to CI as well, to avoid future breakage.

**Comment by alex-statsig** [comment]
This was removed due to https://github.com/googleapis/python-storage/issues/734 a month after, and its been two years now; is there any plan to re-open / re-add this?

**Comment by rmorshea** [comment]
see https://github.com/googleapis/python-storage/issues/393
