### ISSUE TITLE
upload multiple files using one signed url for bucket

### ISSUE THREAD

**Issue by cometta** [googleapis/python-storage#624]
I used 
```
    signed_url = bucket.generate_signed_url(
         version='v4',
         expiration=timedelta(minutes=60),
         method='PUT')
```
and it generated url look like
```
https://storage.googleapis.com/special_bucket?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=cloud-storage-svc-accnt%40<special_account>-.iam.gserviceaccount.com%2F20211018%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20211018T065327Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=xxxx
```

may i know do i need to append additional object_name, when upload file with a PUT at the endpoint?
```
https://storage.googleapis.com/special_bucket/each_file?...
https://storage.googleapis.com/special_bucket/each_file2?...
https://storage.googleapis.com/special_bucket/each_file3?...
```
i get the error on the brower 
```
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
but when i use ```blob.generate_signed_url(..)``` on the same bucket,  i able to upload a file without any error. i already configured CORS for this bucket

Anyone ever successfully upload multiples files using only one signed url?

**Comment by frankyn** [comment]
HI @cometta,

Thanks for your question. You'll need to generate a signed URL per object you wish to upload by using the following method:

https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.generate_signed_url

Signed URLs created on a bucket reference will create a signedURL for bucket specific operations (LIST, GET).

This is slow however there's no alternative right now. 

As for CROSS-ORIGIN issue, the headers might have been cached by the browser client. Recommend clearing cache and trying again.
