### ISSUE TITLE
Allow `raw_download` kwarg for BlobReader

### ISSUE THREAD

**Issue by jphalip** [googleapis/python-storage#666]
The current value for `BlobReader`'s [`VALID_DOWNLOAD_KWARGS`](https://github.com/googleapis/python-storage/blob/ee41b3f883632026e5d0460847122bd1c37b9b2d/google/cloud/storage/fileio.py#L31) constant is:

```python
VALID_DOWNLOAD_KWARGS = {
    "if_generation_match",
    "if_generation_not_match",
    "if_metageneration_match",
    "if_metageneration_not_match",
    "timeout",
    "retry",
}
```

Is there a reason why `raw_download` isn't in the list? I'd like to add it in order to read bytes of a compressed file *without* Cloud Storage doing the decompression.

Because of the current limitation, I have to write my own implementation using the `download_as_bytes(raw_download=True, ...)`. It'd be great if this parameter could be added to the allow-list so I can use the `BlobReader` API instead.

**Comment by cojenco** [comment]
Thanks for filing the issue! I'm looking into this and will make a patch to add the kwarg.
