### ISSUE TITLE
No results when delimiter is set when calling Client.list_blobs

### ISSUE THREAD

**Issue by ali-suleiman-44b20b39** [googleapis/python-storage#672]
#### Environment details

  - OS type and version: MacOS BigSur Version 11.4
  - Python version: Python 3.9.7
  - pip version: pip 21.2.4 
  - `google-cloud-storage` version: `pip show google-cloud-storage`

 `
Name: google-cloud-storage
Version: 1.43.0
Summary: Google Cloud Storage API client library
Home-page: https://github.com/googleapis/python-storage
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/asuleiman/opt/miniconda3/envs/torqata/lib/python3.9/site-packages
Requires: six, google-auth, google-resumable-media, google-api-core, requests, google-cloud-core, protobuf
Required-by:
`

#### Steps to reproduce
1. Run with delimiter set:
```
	from google.cloud import storage
	storage_client = storage.Client()
	r = storage_client.list_blobs(bucket_or_name=bucketname,prefix="match/", delimiter='/')
	c = 0
	for blob in r:
		print(blob.name)
		c+=1
		if c > 5:
			break
```
Result:
```
empty
```

  2. Run without delimiter set:
```
	from google.cloud import storage
	storage_client = storage.Client()
	r = storage_client.list_blobs(bucket_or_name=bucketname,prefix="match/",)
	c = 0
	for blob in r:
		print(blob.name)
		c+=1
		if c > 5:
			break
```
Result:
```
match/asd1/111/2020-04-26.json
match/asd1/111/2020-04-27.json
match/asd1/111/2020-04-28.json
match/asd1/111/2020-04-29.json
match/asd1/111/2020-04-30.json
match/asd1/111/2020-05-01.json
```

**Comment by cojenco** [comment]
Thanks for the question @ali-suleiman-44b20b39

If you specify both `prefix` and `delimiter`, you'll get back only the files directly under the prefix/. As part of the response, you'll also get back an `r.prefixes` entity that lists the "subfolders" under the prefix/. Please refer to the [API doc](https://cloud.google.com/storage/docs/json_api/v1/objects/list?authuser=1).

You can try adding a block of code if you want to view the subdirectories
```

r = storage_client.list_blobs(bucket_or_name=bucketname,prefix="match/", delimiter='/')

if r.prefixes:
    print("prefixes list includes:")
    for sub in r.prefixes:
        print(sub)
```

**Comment by ali-suleiman-44b20b39** [comment]
I see it in the comment lines here: https://cloud.google.com/storage/docs/listing-objects#storage-list-objects-python I will try this out. Thanks

**Comment by cojenco** [comment]
Great, closing the issue for now. Feel free to reopen if you have further questions. Thanks!
