### ISSUE TITLE
Memory leak from client objects

### ISSUE THREAD

**Issue by crwilcox** [googleapis/python-storage#7]
I have a leak that seems to be related to client construction/destruction. Given the following code

```
from google.cloud import storage

def upload_content(client, content):
    bucket = client.bucket('bucket-name')
    blob = bucket.blob('test-hello')
    blob.upload_from_string(content)

if __name__ == '__main__':                  
    content = b"" 
    for i in range(100):
        client = storage.Client()
        upload_content(client, content)
    
    
```

Here is a graph of memory usage over the 100 client creations, small uploads.
<img width="1149" alt="client-created-each-loop-100-iters" src="https://user-images.githubusercontent.com/638797/73031775-e4027380-3df1-11ea-9602-0b4a46aac704.png">

If instead a single client object is reused, you will see no growth
<img width="1160" alt="client-created-once" src="https://user-images.githubusercontent.com/638797/73031814-01374200-3df2-11ea-96eb-7a735e9eea18.png">

I don't believe this is storage specific. It seems something about the client object isn't being cleaned up.

cc: b/147997894

**Comment by tseaver** [comment]
To investigate, try calling `client._http.close()` at the bottom of the loop.

**Comment by tseaver** [comment]
@crwilcox The Python memory allocator only returns stuff sporadically to the OS, and holds on to blocks of 256Kb for small objects expected to have short lifetimes.  That first graph looks pretty much like what I would expect, and doesn't seem to indicate a leak to me.
