### ISSUE TITLE
Create documentation for parallel uploads, suggest multiprocessing.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/python-storage#70]
While working through #69, we found that threading is pretty slow. There is likely work the client can do to become less blocking, but suggesting multiprocessing should help users to stay on the happy path. This is what `gsutil -m` is doing and works very well for multiple uploads.

**Comment by crwilcox** [comment]
Related to https://github.com/googleapis/python-storage/issues/36

**Comment by cojenco** [comment]
Update - this can be closed with  #844

**Comment by meredithslota** [comment]
Assigning so that we remember to close this out once #844 is merged. :)

**Comment by cojenco** [comment]
Now tracking in #844. Closing for deduplication.
