### ISSUE TITLE
False import error

### ISSUE THREAD

**Issue by goodoldneon** [googleapis/python-storage#712]
#### Environment details

  - OS type and version: macOS 12.1
  - Python version: `3.9.9`
  - pip version: `21.2.4`
  - `google-cloud-storage` version: `2.1.0`

#### Steps to reproduce

1. Put `from google.cloud import storage` in one file
2. Put `import google.cloud.billing` in another file
3. Run `mypy .`
4. You'll see `error: Module "google.cloud" has no attribute "storage"`

Full repro here: https://github.com/goodoldneon/google-mypy-repro

#### Code example

See previous section.

#### Stack trace

No stack trace.

**Comment by goodoldneon** [comment]
Note that deleting `.../site-packages/google/cloud/billing/py.typed` also makes the error go away.

**Comment by goodoldneon** [comment]
That fixed the issue for `import google.cloud.billing`... but changing it to `from google.cloud import service_usage` made the issue return. I pushed a new commit to repro repo.

We use many of the `google.cloud` libraries (because y'all are doing awesome work!), and there seem to be weird interactions between them from a type analysis perspective

**Comment by ddelgrosso1** [comment]
I pulled the latest code and ran `mypy .`. I did not receive an errors regarding `storage`. Is. there something else that needs to be done?

**Comment by goodoldneon** [comment]
Huh... it errors for me.

```
$ python -m venv .venv && source .venv/bin/activate
$ pip install -r requirements.txt
$ mypy .
src/b/__init__.py:1: error: Module "google.cloud" has no attribute "storage"
Found 1 error in 1 file (checked 3 source files)
```

**Comment by cojenco** [comment]
hi @goodoldneon thanks for the detailed report. I think `mypy` was able to find the module you were importing, but reported the error due to the missing py.typed marker in python-storage. Our team is planning to add the py.typed marker in Q2, tracking in #621 . 

Meanwhile, you can try adding a `# type: ignore` at the end of the line importing storage, and it should suppress the missing import error. Thanks for your patience!

```
from google.cloud import storage    # type: ignore
```

**Comment by goodoldneon** [comment]
Sounds good!

Also, I found an alternative to `# type: ignore` using dummy stubs. You can see this solution in the `stubs-solution` branch in my repro repo:

https://github.com/goodoldneon/google-mypy-repro/tree/stub-solution

I'll close this issue since I have a stopgap. Thanks so much for the quick help on this!
