### ISSUE TITLE
Unable to unzip password protected .gz files

### ISSUE THREAD

**Issue by abhisharmaa** [googleapis/python-storage#719]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
Am unable to unzip password protected .gz file in GCS using python client.
`     
        blob = source_bucket1.blob(path_list[0])
              zipbytes = io.BytesIO(blob.download_as_string())
              with ZipFile(zipbytes, 'r') as myzip:
   
                             for contentfilename in myzip.namelist()
                                   myzip.setpassword(‘************’)
                                   contentfile = myzip.read(contentfilename)
                                   contentfilename = contentfilename[:-3]
                                   blob1 = bucket.blob(contentfilename)
                                   blob1.upload_from_string(destination_file_name)
       blob.delete()
`

**Comment by Breathtender** [comment]
Hi @abhisharmaa, thanks for your report! I'm trying to reproduce this now, could you share with me what error messages you were getting with this?

**Comment by Breathtender** [comment]
In trying to reproduce this, I was having difficulty with getting ZipFile to work at all, regardless of using GCS or not, so I used pyzipper and I got a working sample. I'm not sure if this is reflective of what you are trying but in this case I just pretty much uploaded a file and downloaded a file.

```
from google.cloud import storage
from zipfile import ZipFile
import pyzipper

secret_password = b'password123'
bucket_name = 'ag-test-turbo-replication'
blob_name = 'zip_blob'

with pyzipper.AESZipFile('new_test.zip',
                         'w',
                         compression=pyzipper.ZIP_LZMA,
                         encryption=pyzipper.WZ_AES) as zf:
    zf.setpassword(secret_password)
    zf.writestr('test.txt', "What ever you do, don't tell anyone!")


client = storage.Client()
bucket = client.bucket(bucket_name)
blob = bucket.blob(blob_name)
blob.upload_from_filename('new_test.zip')

client2 = storage.Client()
bucket2 = client.bucket(bucket_name)
blob2 = bucket.blob(blob_name)
blob2.download_to_filename('downloaded_test.zip')

with pyzipper.AESZipFile('downloaded_test.zip') as zf:
    zf.setpassword(secret_password)
    my_secrets = zf.read('test.txt')
    print(my_secrets)
```

I'm trying to do this with fully in memory now though as I'm guessing that's what you're looking to do and seeing if I can get it to work with ZipFile.

**Comment by abhisharmaa** [comment]
Hi @Breathtender 
Thanks for your response. 
Am trying to read .csv.gz file and using the gzip library but getting below error while downloading it as a file.

`from google.cloud import storage
from zipfile import ZipFile 
storage_client = storage.Client()
source_bucket = '<landing bucket>'
 source_bucket1 = storage_client.bucket(source_bucket)
blob = source_bucket1.blob(path)
        blob.download_to_filename('downloaded_test.csv.gz')
        print('able to download as file')     
        
        with ZipFile('downloaded_test.csv.gz') as myzip:
            myzip.setpassword(pswd)
            print("password set")
            with gzip.open(myzip,mode='rt') as gzfile:
                for line in gzfile:
                    print(line.decode().strip())`

Error : ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

**Comment by Breathtender** [comment]
Hmm, I suppose I'm a bit confused because from what I've seen, .gz doesn't support password protection, and so I'm having a hard time replicating your sample. The 404 code suggests to me this doesn't have anything to do with zip.

When you run this, does it successfully print "able to download as file" and "password set" or is it failing before then?

**Comment by abhisharmaa** [comment]
****UPDATE****
Am able to read .csv.gz password protected file using below logic. All of this is done in memory. It has performance issue if the file is huge but works fine.
```
        bukcet_folder = '/unzip'
        blob = source_bucket1.blob(path)
        zipbytes = io.BytesIO(blob.download_as_string())
        with ZipFile(zipbytes, 'r') as myzip:
            print("Inside the zipfiles loop")
            with myzip.open('filename.csv',pwd=b'password') as myfile:
                print("Inside zip 2 loop")
                contentfile = myfile.read()
                contentfilename = bucket_folder + destination_file_path
                blob1 = source_bucket1.blob(contentfilename)
                blob1.upload_from_string(contentfile)
              ```
