### ISSUE TITLE
2.2.0 breaks typing checks in applications

### ISSUE THREAD

**Issue by syphar** [googleapis/python-storage#734]
In #716 a `py.typed` file was added to tell mypy that it should use the provided type annotations (or stub-files) in this package. 

Problem with that: **there are no type annotations and no stub-file.**

In our application this leads to errors like this: 
<img width="745" alt="grafik" src="https://user-images.githubusercontent.com/540890/158313660-ee4e8c87-3331-4a7a-8b3a-75ff75c94f78.png">

( only on 2.2.0, not in 2.1.0)

#### Environment details

  - Mac OS 12.2.1 
  - Python version: `3.10.2`
  - pip version: `21.2.4`
  - `google-cloud-storage` version: `2.2.0`

#### Steps to reproduce

  1. install 2.2.0 in your application 
  2. use a class anywhere ( it broke for `Client` and `Blob` for me
  3. use `mypy --strict` ( I believe the needed settings are `disallow_untyped_defs` or `disallow_untyped_calls`, but I'm not 100% certain. I can provide my config if that's needed). 

#### Code example

```python
import json
import os
from functools import cache

from google.cloud import storage
from google.oauth2 import service_account

@cache
def _client() -> storage.Client:
    if storage_key := os.environ.get("GOOGLE_CLOUD_STORAGE_KEY", None):
        data = json.loads(storage_key)
        credentials = service_account.Credentials.from_service_account_info(data)

        return storage.Client(  # typing error here 
            credentials=credentials,
            project=data["project_id"],
        )
```

### possible solution 
* add type annotations to all methods & classes 
* remove the `py.typed` marker again.

**Comment by Breathtender** [comment]
You should be able to update your library to 2.2.1 and this problem should be addressed.
Thank you again for bringing the issue to our awareness!
