### ISSUE TITLE
add `setuptools` to dependencies

### ISSUE THREAD

**Issue by cbini** [googleapis/python-storage#740]
If you import this library in an isolated environment, it will fail with `ModuleNotFoundError: No module named 'pkg_resources'` due to the line referenced below. While `setuptools` is a commonly installed alongside Python, it's not a core module, and should be listed as a dependency so that package managers (e.g. pipenv, poetry, pdm) will pick up on it and install it.

https://github.com/googleapis/python-storage/blob/a8fcebb901abc297126cbb183eedbbd603ac5add/google/cloud/storage/_http.py#L19

**Comment by andrewsg** [comment]
You're right! Our automated testing uses setuptools to install the dependencies so it's always installed, but that's not necessarily true of other environments. Thank you for letting us know.
