### ISSUE TITLE
Deprecation/Removal/EOS schedule for v1?

### ISSUE THREAD

**Issue by philippefutureboy** [googleapis/python-storage#763]
Hey there!

What's the schedule for deprecation/removal/End of Service of the v1 API?

We are currently using `google-cloud-storage==1.26.0` since a while ago very reliably, but today we faced an error (`requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))`) and some answers on StackOverflow suggest that this may be due to `v1` being deprecated.

---
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

We have a support case opened already.
I just wanted to have more info wrt to the deprecation/removal of v1 from the team behind the client & the API :)

**Comment by shaffeeullah** [comment]
Hi @philippefutureboy ,

I've tried a few basic operations (such as uploading a file) and I'm unable to reproduce this issue. Can you please provide me with some reproduction steps?

We currently do not have plans for deprecating v1.

**Comment by philippefutureboy** [comment]
Hi @shaffeeullah,

> Can you please provide me with some reproduction steps?

Sure thing!

Here's a minimally reproducible script. Unfortunately there's nothing much to it, because there's not much more happening than that:

```
from google.cloud import storage

BUCKET = '...'
FILENAME = '...'
DEST = '...'

storage_client = storage.Client()
bucket = storage_client.get_bucket(BUCKET)
blob2 = bucket.blob(DEST)
blob2.upload_from_filename(filename=FILENAME)
```

I can provide you with a frozen-requirements.txt, but given that most of the deps in that file are out of date (by several months) and that we handle personal health information, for security reasons I'd like to send you those over a secure channel. Is there any way I can send the deps to you securely?

---

> We currently do not have plans for deprecating v1.

Whew! Thanks for sharing this :)

---

Have a great evening!

**Comment by shaffeeullah** [comment]
Hi @philippefutureboy ,
I'm still unable to reproduce this issue. I see you mentioned earlier that you opened a support ticket; I believe that is the correct way to get the help you're looking for, as it does not seem that this is a client library issue.

**Comment by philippefutureboy** [comment]
Hi @shaffeeullah,

Thanks for your answer!

I was about to comment as well - this is indeed not a library issue. One of our affected client played around on the firewall settings and confirmed that the issue comes from the firewall, which was previously denied by the networking company responsible for the firewall.

Sorry that you had to spend some time on a non-issue. Thanks for your time, very appreciated ✨
