### ISSUE TITLE
Read shapefiles directly from google cloud storage without downloading it and without geopandas

### ISSUE THREAD

**Issue by sonsharma** [googleapis/python-storage#764]
Hello,

I'm trying to read a shapefile placed in one of my buckets in gcs but I'm unable to. I don't want to download the file in my local while reading or use geopandas to read them. I'm running everything on my local and I have all the accesses to gcp bucket. Below is my code:
```
file_path = "gs://my-bucket/country/shapefiles/my-shapefile.shp"
sf_shape = shapefile.Reader(file_path)
```

I'm able to read the csv files perfectly in this manner but I can't read shapfiles directly from gcs. Also, I tried the following but it didn't worked:
```
fs = gcsfs.GCSFileSystem(project="project-name")
with fs.open(file_path, 'w') as f:
     shapefile.Reader(f.read())
```

Also, I tried but it didn't worked:

```
file_path = "country/shapefiles/my-shapefile.shp"
storage_client = storage.Client("project-name")
blob = storage_client.get_bucket(bucket_name).blob(file_path)
sf_shape = shapefile.Reader(blob.download_as_bytes().decode('utf-8'))
fields = [x[0] for x in sf_shape.fields][1:]
```

Please help and guide on ways to resolve this!! Thanks in advance

**Comment by frankyn** [comment]
Hi @sonsharma,

Thanks for filing the issue! 

Could you provide the stacktrace with the failure you saw?

**Comment by sonsharma** [comment]
My bad. I missed putting that. Please see this error. 
```
Traceback (most recent call last):
  File "src/international/etl_shapefiles.py", line 281, in <module>
    main(country)
  File "src/international/etl_shapefiles.py", line 240, in main
    tracts_df = create_tracts(abbrev, f"raw/international/{country}/shapefiles/", local_file_path, engine)
  File "src/international/etl_shapefiles.py", line 122, in create_tracts
    tracts_df = read_shapefile_to_df(files)
  File "/mnt/src/common/utils.py", line 147, in read_shapefile_to_df
    sf_shape = shapefile.Reader(file_path[0])
  File "/usr/local/lib/python3.6/dist-packages/shapefile.py", line 553, in __init__
    self.load(args[0])
  File "/usr/local/lib/python3.6/dist-packages/shapefile.py", line 646, in load
    raise ShapefileException("Unable to open %s.dbf or %s.shp." % (shapeName, shapeName))
shapefile.ShapefileException: Unable to open gs://cb-data-staging-backup/raw/international/Ukraine/shapefiles/Regions/gadm36_UKR_1.dbf or gs://cb-data-staging-backup/raw/international/Ukraine/shapefiles/Regions/gadm36_UKR_1.shp.
```

**Comment by sonsharma** [comment]
My bad. I missed putting that. Here is the error for `sf_shape = shapefile.Reader(file_path)`
```
Traceback (most recent call last):
  File "/mnt/src/common/utils.py", line 147, in read_shapefile_to_df
    sf_shape = shapefile.Reader(file_path)
  File "/usr/local/lib/python3.6/dist-packages/shapefile.py", line 553, in __init__
    self.load(args[0])
  File "/usr/local/lib/python3.6/dist-packages/shapefile.py", line 646, in load
    raise ShapefileException("Unable to open %s.dbf or %s.shp." % (shapeName, shapeName))
shapefile.ShapefileException: Unable to open gs://my-bucket/country/shapefiles/my-shapefile.dbf or gs://my-bucket/country/shapefiles/my-shapefile.shp.
```

For the 2nd -
```
  File "/usr/local/lib/python3.6/dist-packages/shapefile.py", line 884, in __dbfHeader
    raise ShapefileException("Shapefile Reader requires a shapefile or file-like object. (no dbf file found)")
shapefile.ShapefileException: Shapefile Reader requires a shapefile or file-like object. (no dbf file found)
```
For the 3rd-

```
  File "/mnt/src/common/utils.py", line 145, in read_shapefile_to_df
    print(f.read())
io.UnsupportedOperation: not readable
```

**Comment by shaffeeullah** [comment]
Hi @sonsharma ,
It seems that your file is downloading without error and the shapefile library is throwing the exceptions you're seeing. Have you confirmed that this file is readable with that library?

**Comment by vincentschut** [comment]
Hi @sonsharma ,
The problem probably is that "a shapefile" actually must consist of at least 3 mandatory files: a xxx.shp, xxx.shx and xxx.dbf. (see https://en.wikipedia.org/wiki/Shapefile) Only together these make up a proper shapefile. I'm not sure if the shapefile library (or geopandas) actually supports reading shapefiles (= those 3 files) directly from gcs. You'll probably get more appropriate support in their respective help channels.

**Comment by frankyn** [comment]
Adding to @vincentschut,

I see there's a package named [`pyshp`](https://pypi.org/project/pyshp/) which takes in two parameters when reading from file like objects:

> Reading Shapefiles from File-Like Objects
You can also load shapefiles from any Python file-like object using keyword arguments to specify any of the three files. This feature is very powerful and allows you to custom load shapefiles from arbitrary storage formats, such as a protected url or zip file, a serialized object, or in some cases a database.

```python
>>> myshp = open("shapefiles/blockgroups.shp", "rb")
>>> mydbf = open("shapefiles/blockgroups.dbf", "rb")
>>> r = shapefile.Reader(shp=myshp, dbf=mydbf)
```

For Cloud Storage, you'd do something similar to the following:

```python
    storage_client = storage.Client()
    bucket = storage_client.bucket("bucket_name")
    myshp = bucket.blob("shp_name")
    mydbf = bucket.blob("dbf_name")
    
    with myshp.open("r") as shp, mydbf.open("r") as dbf:
        r = shapefile.Reader(shp=shp, dbf=dbf)
        # use r
```

**Comment by shaffeeullah** [comment]
Hi @sonsharma ,

Closing this out, as it doesn't seem to be an issue with this library. Please reopen if we can help you further.
