### ISSUE TITLE
When running tests with plain pytest -k 'not network' tests/unit collection errors

### ISSUE THREAD

**Issue by mcepl** [googleapis/python-storage#771]
When packaging python-storage for openSUSE we hit this issue:

#### Environment details

  - OS type and version: Linux/openSUSE/Factory
  - Python version: Any of Python 3.8, 3.9, and 3.10
  - pip version: 22.0.4
  - `google-cloud-storage` version: 2.3.0

#### Steps to reproduce

  1. Run the test suite:
```
PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-google-cloud-storage-2.3.0-0.x86_64/usr/lib/python3.9/site-packages
PYTHONDONTWRITEBYTECODE=1
pytest-3.9 --ignore=_build.python39 --ignore=_build.python310 --ignore=_build.python38 -v -k 'not network' tests/unit
```

#### Stack trace
```
[   38s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-google-cloud-storage-2.3.0-0.x86_64/usr/lib/python3.9/site-packages
[   38s] + PYTHONDONTWRITEBYTECODE=1
[   38s] + pytest-3.9 --ignore=_build.python39 --ignore=_build.python310 --ignore=_build.python38 -v -k 'not network' tests/unit
[   38s] ============================= test session starts ==============================
[   38s] platform linux -- Python 3.9.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /usr/bin/python3.9
[   38s] cachedir: .pytest_cache
[   38s] rootdir: /home/abuild/rpmbuild/BUILD/google-cloud-storage-2.3.0
[   39s] collecting ... collected 480 items / 4 errors / 476 selected
[   39s]
[   39s] ==================================== ERRORS ====================================
[   39s] __________________ ERROR collecting tests/unit/test__http.py ___________________
[   39s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/google-cloud-storage-2.3.0/tests/unit/test__http.py'.
[   39s] Hint: make sure your test modules/packages have valid Python names.
[   39s] Traceback:
[   39s] tests/unit/test__http.py:21: in <module>
[   39s]     from tests.unit.test__helpers import GCCL_INVOCATION_TEST_CONST
[   39s] E   ModuleNotFoundError: No module named 'tests'
[   39s] _________________ ERROR collecting tests/unit/test__signing.py _________________
[   39s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/google-cloud-storage-2.3.0/tests/unit/test__signing.py'.
[   39s] Hint: make sure your test modules/packages have valid Python names.
[   39s] Traceback:
[   39s] tests/unit/test__signing.py:29: in <module>
[   39s]     from . import _read_local_json
[   39s] E   ImportError: attempted relative import with no known parent package
[   39s] ___________________ ERROR collecting tests/unit/test_blob.py ___________________
[   39s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/google-cloud-storage-2.3.0/tests/unit/test_blob.py'.
[   39s] Hint: make sure your test modules/packages have valid Python names.
[   39s] Traceback:
[   39s] tests/unit/test_blob.py:38: in <module>
[   39s]     from tests.unit.test__helpers import GCCL_INVOCATION_TEST_CONST
[   39s] E   ModuleNotFoundError: No module named 'tests'
[   39s] __________________ ERROR collecting tests/unit/test_client.py __________________
[   39s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/google-cloud-storage-2.3.0/tests/unit/test_client.py'.
[   39s] Hint: make sure your test modules/packages have valid Python names.
[   39s] Traceback:
[   39s] tests/unit/test_client.py:36: in <module>
[   39s]     from tests.unit.test__helpers import GCCL_INVOCATION_TEST_CONST
[   39s] E   ModuleNotFoundError: No module named 'tests'
[   39s] =========================== short test summary info ============================
[   39s] ERROR tests/unit/test__http.py
[   39s] ERROR tests/unit/test__signing.py
[   39s] ERROR tests/unit/test_blob.py
[   39s] ERROR tests/unit/test_client.py
[   39s] !!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!
[   39s] ============================== 4 errors in 0.88s ===============================
```

[Complete build log](https://github.com/googleapis/python-storage/files/8499686/_log.txt) with list of all packages used and all steps taken.

**Comment by tritone** [comment]
The [contributing guide](https://github.com/googleapis/python-storage/blob/main/CONTRIBUTING.rst) indicates that nox should be used to run unit tests. I'll have to ask another library maintainer if it's intended to have support for plain pytest invocations as well (and if so, if this is the way we want to go about it).

**Comment by mcepl** [comment]
> Hmm, I'm trying to make sense of this. Is the python on OpenSUSE doing something different with imports? The relative import and the `from tests.unit.test__helpers import GCCL_INVOCATION_TEST_CONST` all work on my machine; but perhaps there's something I'm not understanding about how python imports may work differently in different environments.

When you run `pytest -v tests/unit` the starting directory for pytest is that (`tests/unit`) and not the root directory of the project. Also, see Python error `"ImportError: attempted relative import with no known parent package"` (it is very complicated).

**Comment by Breathtender** [comment]
Gotcha. Is there a reason you're needing to call pytest directly rather than use nox?
Or is that being automatically called somewhere in the suite?

If it helps, here's the call that nox is actually making to pytest, which works fine
`py.test --quiet --cov=google.cloud.storage --cov=google.cloud --cov=tests.unit --cov-append --cov-config=.coveragerc --cov-report= --cov-fail-under=0 tests/unit`

**Comment by mcepl** [comment]
I don’t think your call to pytest is right.

See [complete build log](https://github.com/googleapis/python-storage/files/8534982/_log.txt)

**Comment by Breathtender** [comment]
I'm curious if this is a new issue?
The GCCL_INVOCATION_TEST_CONST is a new change that was just released in 2.3.0, but the relative import for _read_local_json has been in there for a while now.
I'm wondering if it might be useful to move some of these helpers into a different place that would alleviate this.

I am seeing that when I run that call from above (its literally just what nox generates), I do get errors regarding importing mock, which I believe is what you were looking to address in one of your PRs. I'm guessing that there's some other more subtle setting of the environment that is not clear here that needs to be understood to address this. I'm continuing to research.

**Comment by mcepl** [comment]
And yes of course when running with nox (and I have download `noxfile.py` from git, because you don’t package it in the tarball), I run immediately in problems that you want to do much more than we need (there is no point in our tests to check for the testing coverage):
```
[    9s] + export PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-google-cloud-storage-2.3.0-0.x86_64/usr/lib/python3.9/site-packages
[    9s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-google-cloud-storage-2.3.0-0.x86_64/usr/lib/python3.9/site-packages
[    9s] + python3.9 -mnox -s unit-3.9
[   10s] Running session unit-3.9
[   10s] Creating virtual environment (virtualenv) using python3.9 in .nox/unit-3-9
[   10s] pip install mock pytest pytest-cov -c /home/abuild/rpmbuild/BUILD/google-cloud-storage-2.3.0/testing/constraints-3.9.txt
[   11s] Command pip install mock pytest pytest-cov -c /home/abuild/rpmbuild/BUILD/google-cloud-storage-2.3.0/testing/constraints-3.9.txt failed with exit code 1:
[   11s] ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/abuild/rpmbuild/BUILD/google-cloud-storage-2.3.0/testing/constraints-3.9.txt'
[   11s] Session unit-3.9 failed.
[   11s] error: Bad exit status from /var/tmp/rpm-tmp.DcJHSy (%check)
```
(so now I would have to download `constraints` file, install `pytest-cov`, and a lot of other stuff for something I actually don’t need; and of course, our build environment, as with all distributions, is without network access).

**Comment by tritone** [comment]
@mcepl thanks for the details. Running unit tests for this package from the tarball is not really a supported use case; the tests are intended for development in this package which would mean checking out the source. And I don't think running tests from the tarball is commonly supported in python packages  (feel free to correct me if I'm wrong!).

Definitely take your point, though, that the nox setup is heavier than what a casual contributor to this repo would really need.

Could you speak a little more about what your use case is for running tests from an installation of this package?

**Comment by andrewsg** [comment]
Hi @mcepl, thanks for your report. Running `pytest -k 'not network' tests/unit` works fine for me when run in the git directory. As @tritone supposed, we are not necessarily set up to have tests executed directly from the packaged version. I'll close this for now as his questions about the use case haven't been answered, but feel free to respond later and if needed we can reopen the issue.
