### ISSUE TITLE
Signed blob creation with default credentials does not work

### ISSUE THREAD

**Issue by charan-doxel** [googleapis/python-storage#795]
https://github.com/googleapis/python-storage/blob/3664ddebe8746d0395acd86d5efa1ef973eeac3d/samples/snippets/storage_generate_upload_signed_url_v4.py#L41

Fails with error

AttributeError: you need a private key to sign credentials.the credentials you are currently using <class 'google.oauth2.credentials.Credentials'> just contains a token. see https://googleapis.dev/python/google-api-core/latest/auth.html#setting-up-a-service-account for more details.

**Comment by andrewsg** [comment]
Can you please post the last few lines of the traceback? Feel free to redact as needed. I would like to see if the error is being raised in the Storage or the Auth library in this instance.

**Comment by charan-doxel** [comment]
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/Users/user/.virtualenvs/dev/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 634, in generate_signed_url
    access_token=access_token,
  File "/Users/user/.virtualenvs/dev/lib/python3.7/site-packages/google/cloud/storage/_signing.py", line 550, in generate_signed_url_v4
    ensure_signed_credentials(credentials)
  File "/Users/user/.virtualenvs/dev/lib/python3.7/site-packages/google/cloud/storage/_signing.py", line 56, in ensure_signed_credentials
    "details.".format(type(credentials), SERVICE_ACCOUNT_URL)
AttributeError: you need a private key to sign credentials.the credentials you are currently using <class 'google.oauth2.credentials.Credentials'> just contains a token. see https://googleapis.dev/python/google-api-core/latest/auth.html#setting-up-a-service-account for more details.
>>>

**Comment by andrewsg** [comment]
Thank you. What steps did you follow originally to get the credentials you are using, and how are you passing them into the library?

**Comment by charan-doxel** [comment]
I am using my default google auth for the same. Not using a service account

**Comment by andrewsg** [comment]
Okay. My understanding is that you will need to set up a service account and associated credentials in order to use this feature, because service account credential files include a private key (whereas your default credentials do not). If you follow the instructions here: https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating and set the GOOGLE_APPLICATION_CREDENTIALS env variable or in some other way indicate you'd like to use your SA credentials when creating the Client object in your application, that should resolve your issue.

**Comment by andrewsg** [comment]
I think you will need to actually download a service account json credentials file in order for it to include a private key suitable for signatures.
