### ISSUE TITLE
Documentation: Blob name is not documented as a property

### ISSUE THREAD

**Issue by frankyn** [googleapis/python-storage#82]
Received an internal request to update Storage Documentation to include Blob.name property.

**Comment by HemangChothani** [comment]
@frankyn Can i document  blob.name as a static doc string like `
"""
        property :attr:`name`
            Get the blob's name.
        """ ` as can't use` @property ` decorator to document blob name as a property because it break the existing functionality or is there any other solution to document which i am missing?

**Comment by frankyn** [comment]
Thanks @HemangChothani, could you clarify what would change by using `@property` decorator?
