### ISSUE TITLE
Incorrect example for lifecycle_rules

### ISSUE THREAD

**Issue by bmccutchon** [googleapis/python-storage#832]
The ["note" on `Bucket.lifecycle_rules`](https://github.com/googleapis/python-storage/blob/5e06dc02f54fb54f4d1dbd61d273ffcd96fdd112/google/cloud/storage/bucket.py#L2282) acts as if `lifecycle_rules` returns a `list`, but it actually returns a `generator`.

**Comment by andrewsg** [comment]
Fixing the docstring on this now; I'd like to actually make it consistent with the setter (returning a list) or use some other consistent interface, but can't without breaking backwards compatibility, so this is now on the list for 2.0.
