### ISSUE TITLE
Suppress urllib3 warnings for batch Blob.exists() calls

### ISSUE THREAD

**Issue by VwakeM** [googleapis/python-storage#865]
I am using GCS python client's `Blob.exists()` function to check if a URL actually points to a GCS blob. Since I am doing this for a large number of URLs, I am using `the batch()` function to check 1000 URLs at a time. When I use the two functions as follows, I get the following urllib3 warning for each batch of requests: 

```
# Python code block
CHUNK_SIZE = 1000

index_slices = sliced(range(len(df)), CHUNK_SIZE) #slice the dataframe by chunk size

# Loop over chunks and find the first instance of an invalid URL
for index_slice in index_slices:
  chunk = images.iloc[index_slice] 
  with storage_client.batch():
    for URL in chunk.location:
       try: 
          Exists = storage.Blob(bucket=bucket, name= URL).exists(storage_client)
       except Exception as e:
          print("Something else went wrong") 

```

Warning message printed on each iteration of the loop: 
```
WARNING:urllib3.connectionpool:Failed to parse headers (url=[https://www.googleapis.com:443/batch/storage/v1](https://www.googleapis.com/batch/storage/v1)): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 396, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/response.py", line 72, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
```

Can we suppress this warning as it clogs the output stream?

Note: I am using Colab environment to run the code.

**Comment by cojenco** [comment]
Hi VwakeM, unfortunately `Batch` is not fully supported by the storage client. `Blob.exists()` does not fit well with the current `Batch` design. See #31 for reference.

Further `Batch` support is still under discussion within our team. Looking at your question, I think possible workarounds to suppress the urllib3 warnings might be something like https://github.com/googleapis/python-storage/issues/31#issuecomment-595915315 or https://github.com/diyan/pywinrm/issues/269#issuecomment-518523909. Hope this helps!

**Comment by cojenco** [comment]
Closing this as duplicate. 

If you are still running into 3rd party warnings, please try adding wrapper code in your app, as shown in the previous comment. On the other hand, our team is working on adding clarification to which library methods are incompatible with the batch module. Thanks for your patience.

**Comment by VwakeM** [comment]
Thanks @cojenco makes sense! Apologies, I missed the earlier reply.
