### ISSUE TITLE
Enable authentication when a non-default api_endpoint is set (just like the googleapis/nodejs-storage)

### ISSUE THREAD

**Issue by MadhuPolu** [googleapis/python-storage#895]
**Issue we're facing:**
After version 2.1.0, authorization bearer token is stopped being sent to the custom endpoints (non-default api_endpoint), we forcefully needed to downgrade to the version 2.0.0 to make things work on our end. We had other option like explicitly passing credentials while instantiating the storage client, but this change was needed to be done in all places wherever the client is instantiated, so we just went to downgrade to the version 2.0.0.

**Feature request:**
Since this change [feat: avoid authentication with storage emulator](https://github.com/googleapis/python-storage/pull/679/files#top) was intentional, can you please add a flag to enable the auth for custom endpoints something like in the googleapis/nodejs-storage? 

A flag named **useAuthWithCustomEndpoint** was added in the nodejs storage client library to support the auth with custom endpoints. Just fyi, here are the code changes related to that flag.
 [Allow authentication with custom endpoint](https://github.com/googleapis/nodejs-common/pull/698/files#top)
 [Add support for useAuthWithCustomEndpoint option](https://github.com/googleapis/nodejs-storage/pull/1645/files#top)

**Comment by cojenco** [comment]
Hi @MadhuPolu thanks for filing this issue. Could you please describe your use case in more detail?

If I understand correctly, the desire is for the client to detect the default credentials for the current environment while using a non-default api_endpoint, instead of explicitly passing in credentials. Is my understanding correct? The current design will not bypass auth if you pass in credentials when instantiating a client.

**Comment by MadhuPolu** [comment]
Yes @cojenco, you're correct, we need the client to detect the default credentials while using a non-default api_endpoint. And we don't want to pass any credentials explicitly when instantiating a client as we heavily depend on [ADC](https://cloud.google.com/docs/authentication/application-default-credentials) (Application Default Credentials).

Please let me know if you need any more details.

Trivials: 
1. We also use other language GCS clients Go, Node.js, Java, PHP. All are supporting the ADC out of the box when the non-default api_endpoint is set, Node.js enabled it through a flag.
2. One year ago, we faced the similar problem with googleapis/nodejs-storage, here is [the nodejs-storage bug ](https://github.com/googleapis/nodejs-storage/issues/1555) we reported. 

ADC is a strategy used by [Cloud Client Libraries and Google API Client Libraries](https://cloud.google.com/apis/docs/client-libraries-explained) to automatically find credentials based on the application environment, and use those credentials to authenticate to Google Cloud APIs.

**Comment by cojenco** [comment]
Thank you for the additional context👍 I'm working with our team to address this.

**Comment by MadhuPolu** [comment]
Hi @cojenco it seems [this feature changes](https://github.com/googleapis/python-storage/commit/4862a9c34fcd9524f31312227a2ccf5e376f39fa) got reverted, may know the latest update on this?

PS:  We don't have any option other than using lower version 2.0.0 until you folks decide the direction for changes.

**Comment by MadhuPolu** [comment]
@cojenco never mind, found the new open PR https://github.com/googleapis/python-storage/pull/941

**Comment by cojenco** [comment]
Hi @MadhuPolu the fix is now ready in [v2.7.0](https://github.com/googleapis/python-storage/releases/tag/v2.7.0) Thanks again for reporting!
