### ISSUE TITLE
Jövőnemzedék

### ISSUE THREAD

**Issue by BennZoll** [googleapis/python-storage#90]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by HemangChothani** [comment]
@BennZoll It is not clear what the issue / feature request is about, unfortunately. Could you please update the description?

**Comment by BennZoll** [comment]
> Thanks for stopping by to let us know something could be better!
> 
> **PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
> 
>  **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
>  **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
>  **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
>  **Additional context**
> Add any other context or screenshots about the feature request here.
>

**Comment by frankyn** [comment]
Hi @BennZoll, thanks for filing the issue. At the moment it's not actionable based on the information provided. I'm closing this issue. You're welcome to another issue, thank you for your patience.
