### ISSUE TITLE
Blob.exists() making multiple calls

### ISSUE THREAD

**Issue by nitishxp** [googleapis/python-storage#913]
Lib:  google-cloud-storage==2.4.0
python : Cloud Function python 3.9

Hi, I am finding that using blob.exists() is making 2 extra call instead of 1 API call

Snippet:

```
event_bucket = client.get_bucket(<bucket>)
blob = event_bucket.blob("path to blob")
if blob.exists():
   pass
```
Below is the log
```
{"severity": "DEBUG", "message": "https://storage.googleapis.com:443 \"GET /storage/v1/b/<bucket>?projection=noAcl&prettyPrint=false HTTP/1.1\" 200 690"}
{"severity": "DEBUG", "message": "https://storage.googleapis.com:443 \"GET /storage/v1/b/<bucket>/o/test.txt?fields=name&prettyPrint=false HTTP/1.1\" 404 205"}
{"severity": "DEBUG", "message": "https://storage.googleapis.com:443 \"GET /storage/v1/b/<bucket>?projection=noAcl&prettyPrint=false HTTP/1.1\" 200 690"}
{"severity": "DEBUG", "message": "https://storage.googleapis.com:443 \"GET /storage/v1/b/<bucket>/o/test.txt?fields=name&prettyPrint=false HTTP/1.1\" 404 205"}
{"severity": "DEBUG", "message": "https://storage.googleapis.com:443 \"GET /storage/v1/b/<bucket>?projection=noAcl&prettyPrint=false HTTP/1.1\" 200 690"}
{"severity": "DEBUG", "message": "https://storage.googleapis.com:443 \"GET /storage/v1/b/<bucket>/o/test.txt?fields=name&prettyPrint=false HTTP/1.1\" 404 205"}
```

**Comment by tritone** [comment]
The first call is from `client.get_bucket()`, which makes an API call to fetch bucket metadata. You can skip this call by using `client.bucket()` instead I believe.

Let me know if this does the trick:
```
event_bucket = client.bucket(<bucket>)
blob = event_bucket.blob("path to blob")
if blob.exists():
   pass
```

**Comment by nitishxp** [comment]
@tritone In the logs you can see `/storage/v1/b/<bucket>/o/test.txt?` is being printed 3 times

**Comment by nitishxp** [comment]
@tritone  i tried but still for the object I am getting duplicate API calls

**Comment by tritone** [comment]
@nitishxp I was not able to reproduce this locally; I only see one call to GET the object when running it myself. I suspect there is an issue with your logging, or maybe your code is calling the snippet more times than you expect.

**Comment by nitishxp** [comment]
Thanks @tritone
