### ISSUE TITLE
Update conformance tests to fit the new format

### ISSUE THREAD

**Issue by IlyaFaer** [googleapis/python-storage#92]
Bring Storage conformance tests exactly to [v4_signatures.json](https://github.com/googleapis/conformance-tests/blob/master/storage/v1/v4_signatures.json) format (see [comment](https://github.com/googleapis/python-storage/pull/87#issuecomment-606726025)). This should be done after merging [POST policies PR](https://github.com/googleapis/python-storage/pull/87).

/cc @frankyn, @crwilcox

**Comment by IlyaFaer** [comment]
@frankyn, in `signingV4Tests` we have `expiration` as `str`:
https://github.com/googleapis/conformance-tests/blob/24a5e2373d1240ff3538f9999888053ba8b6a539/storage/v1/v4_signatures.json#L8

But in `postPolicyV4Tests` it is `int`:
https://github.com/googleapis/conformance-tests/blob/24a5e2373d1240ff3538f9999888053ba8b6a539/storage/v1/v4_signatures.json#L281

Should we bring this to a single type?

**Comment by frankyn** [comment]
I just saw this question.

Yes, bring it in as an int. I'm surprised we didnt' catch that during the signed URLs or Post Policies.
